"""Generate fetish_pack tag YAML, tree JS, rules, and conflicts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog_fetish_data import (  # noqa: E402
    FETISH_CATALOG,
    FETISH_COMPAT_WARNINGS,
    FETISH_CONFLICT_GROUPS,
    FETISH_GROUP_LABELS,
)

PACK_ROOT = Path(__file__).resolve().parents[1] / "egodary" / "content" / "fetish_pack"
TAGS_ROOT = PACK_ROOT / "tags"
JS_TREE = Path(__file__).resolve().parents[1] / "egodary" / "web" / "static" / "js" / "fetish-tree-data.js"


def slug(label: str) -> str:
    return (
        label.lower()
        .replace("(", "")
        .replace(")", "")
        .replace("'", "")
        .replace('"', "")
        .replace("/", " ")
        .replace("+", " ")
        .replace("&", " ")
        .replace("-", " ")
        .replace(",", "")
        .replace(".", "")
        .replace("…", "")
        .replace("  ", " ")
        .strip()
        .replace(" ", "_")
    )


def fetish_item(label: str, subgroup: str) -> dict:
    ill = label.lower()
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": f"{ill}, erotic detail",
            "zimage_turbo": f"with {ill}",
        },
    }


def build_items() -> tuple[list[dict], dict[str, str], dict[str, list[str]]]:
    items: list[dict] = []
    label_to_id: dict[str, str] = {}
    subgroups: dict[str, list[str]] = {sg: [] for sg in FETISH_CATALOG}
    used: set[str] = set()

    for subgroup, labels in FETISH_CATALOG.items():
        for label in labels:
            item_id = slug(label)
            if item_id in used:
                item_id = f"{subgroup}_{item_id}"
            used.add(item_id)
            item = fetish_item(label, subgroup)
            item["id"] = item_id
            items.append(item)
            label_to_id[label] = item_id
            subgroups[subgroup].append(item_id)

    return items, label_to_id, subgroups


def write_elements_yaml(items: list[dict]) -> None:
    TAGS_ROOT.mkdir(parents=True, exist_ok=True)
    for old in TAGS_ROOT.glob("*.yaml"):
        if old.name != "elements.yaml":
            old.unlink()
    payload = {"id": "fetish.elements", "title": "Fetish Elements", "items": items}
    (TAGS_ROOT / "elements.yaml").write_text(
        yaml.dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def write_fetish_tree_js() -> None:
    tree: list[dict] = []
    for subgroup, labels in FETISH_CATALOG.items():
        tree.append(
            {
                "id": f"fetish_{subgroup}",
                "label": FETISH_GROUP_LABELS.get(subgroup, subgroup.replace("_", " ").title()),
                "children": [
                    {
                        "id": f"fetish_{subgroup}_items",
                        "label": FETISH_GROUP_LABELS.get(subgroup, subgroup.replace("_", " ").title()),
                        "field": "elements",
                        "categoryId": "fetish.elements",
                        "subgroup": subgroup,
                        "multi": True,
                    }
                ],
            }
        )
    JS_TREE.parent.mkdir(parents=True, exist_ok=True)
    JS_TREE.write_text(
        f"/* Auto-generated by build_fetish_catalog.py */\nwindow.FETISH_TREE = {json.dumps(tree, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )


def write_conflicts_yaml(label_to_id: dict[str, str]) -> None:
    groups = []
    for raw_ids in FETISH_CONFLICT_GROUPS:
        groups.append(
            {
                "category_id": "fetish.elements",
                "ids": [label_to_id[label] for label in raw_ids],
                "reason": "Mutually exclusive fetish elements",
            }
        )
    payload = {"groups": groups}
    (PACK_ROOT / "conflicts.yaml").write_text(
        yaml.dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def write_fetish_rules_yaml(label_to_id: dict[str, str], subgroups: dict[str, list[str]]) -> None:
    warnings: list[dict] = []
    for rule in FETISH_COMPAT_WARNINGS:
        entry = {"message": rule["message"]}
        if "labels" in rule:
            entry["element_ids"] = [label_to_id[lb] for lb in rule["labels"]]
        warnings.append(entry)

    payload = {
        "max_per_subgroup": 6,
        "max_elements": 12,
        "subgroups": subgroups,
        "compatibility_warnings": warnings,
    }
    (PACK_ROOT / "fetish_rules.yaml").write_text(
        yaml.dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def write_external_skip_yaml(label_to_id: dict[str, str]) -> None:
    payload = {
        "rules": {
            label_to_id["Latex catsuit (if not in outfit)"]: [
                {"field": "outfit.dress", "equals": "black_latex_long_dress"},
                {"field": "outfit.dress", "equals": "latex_catsuit"},
                {"field": "outfit.top", "equals": "latex_corset_top"},
            ],
            label_to_id["Ahegao face"]: [
                {"field": "face.facial_expression", "equals": "classic_ahegao_tongue_out_eyes_rolled_up"},
                {"field": "face.facial_expression", "equals": "subtle_ahegao_half_lidded"},
            ],
        }
    }
    (PACK_ROOT / "external_skip.yaml").write_text(
        yaml.dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def main() -> None:
    items, label_to_id, subgroups = build_items()
    write_elements_yaml(items)
    write_fetish_tree_js()
    write_conflicts_yaml(label_to_id)
    write_fetish_rules_yaml(label_to_id, subgroups)
    write_external_skip_yaml(label_to_id)
    print(f"Wrote {len(items)} fetish elements across {len(FETISH_CATALOG)} subgroups to {TAGS_ROOT}")


if __name__ == "__main__":
    main()
