"""Generate character_pack tag YAML files and UI tree."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog_character_data import (  # noqa: E402
    CHARACTER_CATALOG,
    CHARACTER_FIELD_LABELS,
    CHARACTER_SUBGROUP_LABELS,
    CHARACTER_TREE_GROUPS,
)

ROOT = Path(__file__).resolve().parents[1] / "egodary" / "content" / "character_pack" / "tags"
JS_OUT = Path(__file__).resolve().parents[1] / "egodary" / "web" / "static" / "js" / "character-tree-data.js"
MANIFEST = Path(__file__).resolve().parents[1] / "egodary" / "content" / "character_pack" / "manifest.toml"


def slug(label: str) -> str:
    return (
        label.lower()
        .replace("(", "")
        .replace(")", "")
        .replace("'", "")
        .replace('"', "")
        .replace("–", " ")
        .replace("-", " ")
        .replace("/", " ")
        .replace("+", " ")
        .replace("&", " ")
        .replace(",", "")
        .replace("  ", " ")
        .strip()
        .replace(" ", "_")
    )


def character_item(label: str, subgroup: str, *, field: str) -> dict:
    ill = label.lower()
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": f"{ill}, detailed body",
            "zimage_turbo": f"with {ill}",
        },
    }


def items_from_groups(field: str, groups: dict[str, list[str]]) -> list[dict]:
    items: list[dict] = []
    used: set[str] = set()
    for subgroup, labels in groups.items():
        for label in labels:
            item_id = slug(label)
            if item_id in used:
                item_id = f"{subgroup}_{item_id}"
            used.add(item_id)
            item = character_item(label, subgroup, field=field)
            item["id"] = item_id
            items.append(item)
    return items


def write_category(field: str, items: list[dict]) -> None:
    cat_id = f"character.{field}"
    title = CHARACTER_FIELD_LABELS.get(field, field.replace("_", " ").title())
    path = ROOT / f"{field}.yaml"
    payload = {"id": cat_id, "title": title, "items": items}
    path.write_text(yaml.dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")


def _leaf(field: str, label: str, subgroup: str, *, multi: bool = False) -> dict:
    node: dict = {
        "id": f"character_{field}_{subgroup}",
        "label": label,
        "field": field,
        "categoryId": f"character.{field}",
        "subgroup": subgroup,
    }
    if multi:
        node["multi"] = True
    return node


def _field_group(field: str, label: str, *, multi: bool = False) -> dict:
    groups = CHARACTER_CATALOG[field]
    labels_map = CHARACTER_SUBGROUP_LABELS.get(field, {})
    children = [
        _leaf(field, labels_map.get(subgroup, subgroup.replace("_", " ").title()), subgroup, multi=multi)
        for subgroup in groups
    ]
    return {"id": f"character_group_{field}", "label": label, "children": children}


def build_tree_nodes(groups: list[dict]) -> list[dict]:
    tree: list[dict] = []
    for group in groups:
        if "children" in group:
            # proportions: each child is its own field group with one subgroup
            prop_children = []
            for child in group["children"]:
                field = child["field"]
                subgroup = next(iter(CHARACTER_CATALOG[field]))
                prop_children.append(
                    _leaf(field, child["label"], subgroup, multi=child.get("multi", False))
                )
            tree.append(
                {
                    "id": f"character_group_{slug(group['label'])}",
                    "label": group["label"],
                    "children": prop_children,
                }
            )
            continue
        tree.append(_field_group(group["field"], group["label"], multi=group.get("multi", False)))
    return tree


def write_character_tree_js() -> None:
    tree = build_tree_nodes(CHARACTER_TREE_GROUPS)
    payload = f"/* Auto-generated by build_character_catalog.py */\nwindow.CHARACTER_TREE = {json.dumps(tree, ensure_ascii=False, indent=2)};\n"
    JS_OUT.write_text(payload, encoding="utf-8")


def write_manifest() -> None:
    if MANIFEST.is_file():
        return
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        """[plugin]
id = "character_pack"
name = "Character Pack"
version = "1.0.0"
kind = "content_pack"
author = "eGOdary"
requires_core = ">=0.1"
depends_on = []

[content]
tags_dir = "tags"
""",
        encoding="utf-8",
    )


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    write_manifest()
    for field, groups in CHARACTER_CATALOG.items():
        write_category(field, items_from_groups(field, groups))
    write_character_tree_js()
    print(f"Wrote character catalog to {ROOT}")


if __name__ == "__main__":
    main()
