"""Generate style_pack tag YAML files, tree JS, and rules."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog_style_data import (  # noqa: E402
    STYLE_CATALOG,
    STYLE_COMPAT_WARNINGS,
    STYLE_EXCLUSIVE_GROUPS,
    STYLE_FIELD_LABELS,
    STYLE_SUBGROUP_LABELS,
)

PACK_ROOT = Path(__file__).resolve().parents[1] / "egodary" / "content" / "style_pack"
TAGS_ROOT = PACK_ROOT / "tags"
JS_TREE = Path(__file__).resolve().parents[1] / "egodary" / "web" / "static" / "js" / "style-tree-data.js"


def slug(label: str) -> str:
    return (
        label.lower()
        .replace("(", "")
        .replace(")", "")
        .replace("'", "")
        .replace('"', "")
        .replace("/", " ")
        .replace("+", " ")
        .replace("&", " ")
        .replace("-", " ")
        .replace(",", "")
        .replace("  ", " ")
        .strip()
        .replace(" ", "_")
    )


def style_item(label: str, subgroup: str) -> dict:
    ill = label.lower()
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": ill,
            "zimage_turbo": ill,
        },
    }


def artist_name_from_label(label: str) -> str:
    lowered = label.lower()
    if lowered.endswith(" style"):
        return label[: -len(" style")].strip()
    return label.strip()


def artist_style_item(label: str, subgroup: str) -> dict:
    name = artist_name_from_label(label)
    ill = label.lower()
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": f"in the style of {name}, {ill}, heavily inspired by {name}",
            "zimage_turbo": f"in the style of {name}, heavily inspired by {name}, artstation, {name}",
        },
    }


STYLE_ITEM_FACTORIES: dict[str, object] = {
    "art_style": style_item,
    "artist_style": artist_style_item,
    "quality": style_item,
    "aesthetic": style_item,
    "technique": style_item,
}


def items_from_groups(field: str, groups: dict[str, list[str]]) -> list[dict]:
    factory = STYLE_ITEM_FACTORIES.get(field, style_item)
    items: list[dict] = []
    used: set[str] = set()
    for subgroup, labels in groups.items():
        for label in labels:
            item_id = slug(label)
            if item_id in used:
                item_id = f"{subgroup}_{item_id}"
            used.add(item_id)
            item = factory(label, subgroup)
            item["id"] = item_id
            items.append(item)
    return items


def write_category(field: str, items: list[dict]) -> None:
    cat_id = f"style.{field}"
    title = STYLE_FIELD_LABELS.get(field, field.replace("_", " ").title())
    path = TAGS_ROOT / f"{field}.yaml"
    payload = {"id": cat_id, "title": title, "items": items}
    path.write_text(yaml.dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")


def write_style_tree_js() -> None:
    tree: list[dict] = []
    for field, groups in STYLE_CATALOG.items():
        labels = STYLE_SUBGROUP_LABELS.get(field, {})
        children = []
        for subgroup in groups:
            child: dict = {
                "id": f"style_{field}_{subgroup}",
                "label": labels.get(subgroup, subgroup.replace("_", " ").title()),
                "field": field,
                "categoryId": f"style.{field}",
                "subgroup": subgroup,
            }
            if field in ("quality", "aesthetic", "technique"):
                child["multi"] = True
            children.append(child)
        tree.append(
            {
                "id": f"style_{field}",
                "label": STYLE_FIELD_LABELS.get(field, field.replace("_", " ").title()),
                "children": children,
            }
        )
    JS_TREE.parent.mkdir(parents=True, exist_ok=True)
    JS_TREE.write_text(
        f"/* Auto-generated by build_style_catalog.py */\n"
        f"window.STYLE_TREE = {json.dumps(tree, indent=2)};\n",
        encoding="utf-8",
    )


def write_rules_yaml(id_index: dict[str, dict[str, str]]) -> None:
    exclusive_groups = []
    for group in STYLE_EXCLUSIVE_GROUPS:
        exclusive_groups.append({"ids": group, "message": "Conflicting art styles — kept the most recent selection."})

    warnings: list[dict] = []
    for rule in STYLE_COMPAT_WARNINGS:
        entry = {"message": rule["message"]}
        if "art_style_subgroup" in rule:
            subgroup = rule["art_style_subgroup"]
            entry["art_style_ids"] = [
                id_index["art_style"][label]
                for labels in STYLE_CATALOG["art_style"].values()
                for label in labels
                if subgroup in STYLE_CATALOG["art_style"]
                and label in STYLE_CATALOG["art_style"][subgroup]
            ]
        if "quality_ids" in rule:
            entry["quality_ids"] = rule["quality_ids"]
        if "aesthetic_ids" in rule:
            entry["aesthetic_ids"] = rule["aesthetic_ids"]
        warnings.append(entry)

    payload = {
        "single_select_fields": ["art_style", "artist_style"],
        "multi_select_limits": {"quality": 8, "aesthetic": 56, "technique": 6},
        "exclusive_art_style_groups": STYLE_EXCLUSIVE_GROUPS,
        "blend_exceptions": sorted({"semi_realistic_anime", "realistic_anime_blend"}),
        "compatibility_warnings": warnings,
    }
    (PACK_ROOT / "style_rules.yaml").write_text(
        yaml.dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def main() -> None:
    TAGS_ROOT.mkdir(parents=True, exist_ok=True)
    PACK_ROOT.mkdir(parents=True, exist_ok=True)
    manifest = PACK_ROOT / "manifest.toml"
    if not manifest.exists():
        manifest.write_text(
            '[plugin]\n'
            'id = "style_pack"\n'
            'name = "Style Pack"\n'
            'version = "1.0.0"\n'
            'kind = "content_pack"\n'
            'author = "eGOdary"\n'
            'requires_core = ">=0.1"\n'
            'depends_on = []\n\n'
            '[content]\n'
            'tags_dir = "tags"\n',
            encoding="utf-8",
        )

    id_index: dict[str, dict[str, str]] = {field: {} for field in STYLE_CATALOG}
    total = 0
    for field, groups in STYLE_CATALOG.items():
        items = items_from_groups(field, groups)
        for item in items:
            id_index[field][item["label"]] = item["id"]
        write_category(field, items)
        total += len(items)

    write_style_tree_js()
    write_rules_yaml(id_index)
    print(f"Wrote {total} style tags across {len(STYLE_CATALOG)} categories to {TAGS_ROOT}")


if __name__ == "__main__":
    main()
