"""Generate environment_pack tag YAML files, tree JS, and rules."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog_environment_data import (  # noqa: E402
    ENVIRONMENT_CATALOG,
    ENVIRONMENT_COMPAT_WARNINGS,
    ENVIRONMENT_FIELD_LABELS,
    ENVIRONMENT_LOCATION_GROUPS,
    ENVIRONMENT_SUBGROUP_LABELS,
)

PACK_ROOT = Path(__file__).resolve().parents[1] / "egodary" / "content" / "environment_pack"
TAGS_ROOT = PACK_ROOT / "tags"
JS_TREE = Path(__file__).resolve().parents[1] / "egodary" / "web" / "static" / "js" / "environment-tree-data.js"


def slug(label: str) -> str:
    return (
        label.lower()
        .replace("(", "")
        .replace(")", "")
        .replace("'", "")
        .replace('"', "")
        .replace("/", " ")
        .replace("+", " ")
        .replace("&", " ")
        .replace("-", " ")
        .replace(",", "")
        .replace("–", " ")
        .replace("—", " ")
        .replace("  ", " ")
        .strip()
        .replace(" ", "_")
    )


def environment_item(label: str, subgroup: str) -> dict:
    ill = label.lower()
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": f"{ill}, detailed environment",
            "zimage_turbo": f"in {ill}",
        },
    }


def situation_item(label: str, subgroup: str) -> dict:
    ill = label.lower()
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": f"{ill}, cinematic scene composition",
            "zimage_turbo": f"{ill}, dramatic scene",
        },
    }


ITEM_FACTORIES: dict[str, object] = {
    "location": environment_item,
    "situation": situation_item,
    "modifiers": environment_item,
}


def items_from_groups(field: str, groups: dict[str, list[str]]) -> list[dict]:
    factory = ITEM_FACTORIES.get(field, environment_item)
    items: list[dict] = []
    used: set[str] = set()
    for subgroup, labels in groups.items():
        for label in labels:
            item_id = slug(label)
            if item_id in used:
                item_id = f"{subgroup}_{item_id}"
            used.add(item_id)
            item = factory(label, subgroup)
            item["id"] = item_id
            items.append(item)
    return items


def write_category(field: str, items: list[dict]) -> None:
    cat_id = f"environment.{field}"
    title = ENVIRONMENT_FIELD_LABELS.get(field, field.replace("_", " ").title())
    path = TAGS_ROOT / f"{field}.yaml"
    payload = {"id": cat_id, "title": title, "items": items}
    path.write_text(yaml.dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")


SCENE_TREE_LEAVES = [
    {"field": "time", "label": "Time of Day", "categoryId": "scene.time"},
    {"field": "weather", "label": "Weather", "categoryId": "scene.weather"},
    {"field": "season", "label": "Season", "categoryId": "scene.season"},
]


def write_environment_tree_js() -> None:
    tree: list[dict] = [
        {
            "id": "environment_scene",
            "label": "Time & Weather",
            "children": [
                {
                    "id": f"environment_scene_{leaf['field']}",
                    "label": leaf["label"],
                    "field": leaf["field"],
                    "stateSection": "scene",
                    "categoryId": leaf["categoryId"],
                }
                for leaf in SCENE_TREE_LEAVES
            ],
        }
    ]
    for field, groups in ENVIRONMENT_CATALOG.items():
        labels = ENVIRONMENT_SUBGROUP_LABELS.get(field, {})
        children = []
        for subgroup in groups:
            child: dict = {
                "id": f"environment_{field}_{subgroup}",
                "label": labels.get(subgroup, subgroup.replace("_", " ").title()),
                "field": field,
                "categoryId": f"environment.{field}",
                "subgroup": subgroup,
            }
            if field == "modifiers":
                child["multi"] = True
            children.append(child)
        tree.append(
            {
                "id": f"environment_{field}",
                "label": ENVIRONMENT_FIELD_LABELS.get(field, field.replace("_", " ").title()),
                "children": children,
            }
        )
    JS_TREE.parent.mkdir(parents=True, exist_ok=True)
    JS_TREE.write_text(
        f"/* Auto-generated by build_environment_catalog.py */\n"
        f"window.ENVIRONMENT_TREE = {json.dumps(tree, indent=2)};\n",
        encoding="utf-8",
    )


def write_rules_yaml(label_index: dict[str, dict[str, str]]) -> None:
    location_groups: dict[str, list[str]] = {}
    for group, labels in ENVIRONMENT_LOCATION_GROUPS.items():
        location_groups[group] = [label_index["location"][lb] for lb in labels]

    warnings: list[dict] = []
    for rule in ENVIRONMENT_COMPAT_WARNINGS:
        entry: dict = {"message": rule["message"]}
        if "location_group" in rule:
            entry["location_ids"] = location_groups[rule["location_group"]]
        if "light_type_labels" in rule:
            from catalog_lighting_data import LIGHTING_CATALOG

            light_index: dict[str, str] = {}
            for subgroup, labels in LIGHTING_CATALOG["light_type"].items():
                for label in labels:
                    item_id = slug(label)
                    light_index[label] = item_id
            entry["light_type_ids"] = [light_index[lb] for lb in rule["light_type_labels"]]
        if "fetish_group" in rule:
            entry["fetish_group"] = rule["fetish_group"]
            entry["fetish_min_level"] = rule.get("fetish_min_level", 4)
        if "face_expression_group" in rule:
            entry["face_expression_group"] = rule["face_expression_group"]
        warnings.append(entry)

    payload = {
        "location_groups": location_groups,
        "compatibility_warnings": warnings,
        "single_select_fields": ["location", "situation"],
        "multi_select_fields": {"modifiers": 2},
        "indoor_groups": ["indoor"],
    }
    (PACK_ROOT / "environment_rules.yaml").write_text(
        yaml.dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def main() -> None:
    TAGS_ROOT.mkdir(parents=True, exist_ok=True)
    PACK_ROOT.mkdir(parents=True, exist_ok=True)
    label_index: dict[str, dict[str, str]] = {field: {} for field in ENVIRONMENT_CATALOG}
    total = 0

    for field, groups in ENVIRONMENT_CATALOG.items():
        items = items_from_groups(field, groups)
        for item in items:
            label_index[field][item["label"]] = item["id"]
        write_category(field, items)
        total += len(items)

    write_environment_tree_js()
    write_rules_yaml(label_index)
    print(f"Wrote {total} environment tags across {len(ENVIRONMENT_CATALOG)} categories to {TAGS_ROOT}")


if __name__ == "__main__":
    main()
