"""Generate face_pack tag YAML files."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog_face_data import FACE_CATALOG, FACE_FIELD_LABELS, FACE_SUBGROUP_LABELS  # noqa: E402

ROOT = Path(__file__).resolve().parents[1] / "egodary" / "content" / "face_pack" / "tags"
JS_OUT = Path(__file__).resolve().parents[1] / "egodary" / "web" / "static" / "js" / "face-tree-data.js"

# Nested under another face tree node (not a separate top-level group).
NESTED_FACE_CATEGORIES: dict[str, dict[str, str]] = {
    "eye_color": {"under": "eyes", "field": "eye_color"},
}


def slug(label: str) -> str:
    return (
        label.lower()
        .replace("(", "")
        .replace(")", "")
        .replace("'", "")
        .replace('"', "")
        .replace("/", " ")
        .replace("+", " ")
        .replace("&", " ")
        .replace("-", " ")
        .replace(",", "")
        .replace("  ", " ")
        .strip()
        .replace(" ", "_")
    )


def face_item(label: str, subgroup: str, *, cat_key: str = "") -> dict:
    ill = label.lower()
    if cat_key == "eye_color":
        if subgroup == "fantasy_glowing":
            if not ill.endswith("eyes"):
                ill = f"{ill} eyes"
        else:
            if not ill.endswith("eyes"):
                ill = f"{ill} eyes"
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": f"{ill}, detailed face",
            "zimage_turbo": f"with {ill}",
        },
    }


def items_from_groups(groups: dict[str, list[str]], *, cat_key: str = "") -> list[dict]:
    items: list[dict] = []
    used: set[str] = set()
    for subgroup, labels in groups.items():
        for label in labels:
            item_id = slug(label)
            if item_id in used:
                item_id = f"{subgroup}_{item_id}"
            used.add(item_id)
            items.append(face_item(label, subgroup, cat_key=cat_key))
            items[-1]["id"] = item_id
    return items


def write_category(cat_key: str, items: list[dict]) -> None:
    cat_id = f"face.{cat_key}"
    title = FACE_FIELD_LABELS.get(cat_key, cat_key.replace("_", " ").title())
    path = ROOT / f"{cat_key}.yaml"
    payload = {"id": cat_id, "title": title, "items": items}
    path.write_text(yaml.dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")


def write_face_tree_js() -> None:
    tree: list[dict] = []
    nested_keys = set(NESTED_FACE_CATEGORIES)
    for cat_key, groups in FACE_CATALOG.items():
        if cat_key in nested_keys:
            continue
        labels = FACE_SUBGROUP_LABELS.get(cat_key, {})
        children = []
        for subgroup in groups:
            children.append(
                {
                    "id": f"face_{cat_key}_{subgroup}",
                    "label": labels.get(subgroup, subgroup.replace("_", " ").title()),
                    "field": cat_key,
                    "categoryId": f"face.{cat_key}",
                    "subgroup": subgroup,
                }
            )
        for nested_key, cfg in NESTED_FACE_CATEGORIES.items():
            if cfg["under"] != cat_key:
                continue
            nested_groups = FACE_CATALOG[nested_key]
            nested_labels = FACE_SUBGROUP_LABELS.get(nested_key, {})
            for subgroup in nested_groups:
                children.append(
                    {
                        "id": f"face_{cat_key}_{nested_key}_{subgroup}",
                        "label": nested_labels.get(subgroup, subgroup.replace("_", " ").title()),
                        "field": cfg["field"],
                        "categoryId": f"face.{nested_key}",
                        "subgroup": subgroup,
                    }
                )
        tree.append(
            {
                "id": f"face_{cat_key}",
                "label": FACE_FIELD_LABELS.get(cat_key, cat_key.replace("_", " ").title()),
                "children": children,
            }
        )
    import json

    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.write_text(
        f"/* Auto-generated by build_face_catalog.py */\nwindow.FACE_TREE = {json.dumps(tree, indent=2)};\n",
        encoding="utf-8",
    )


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    total = 0
    for cat_key, groups in FACE_CATALOG.items():
        items = items_from_groups(groups, cat_key=cat_key)
        write_category(cat_key, items)
        total += len(items)
    write_face_tree_js()
    print(f"Wrote {total} face tags across {len(FACE_CATALOG)} categories to {ROOT}")


if __name__ == "__main__":
    main()
