"""Generate lighting_pack tag YAML files, tree JS, presets, and rules."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog_lighting_data import (  # noqa: E402
    LIGHTING_CATALOG,
    LIGHTING_COMPAT_WARNINGS,
    LIGHTING_FIELD_LABELS,
    LIGHTING_PRESETS,
    LIGHTING_SUBGROUP_LABELS,
)

PACK_ROOT = Path(__file__).resolve().parents[1] / "egodary" / "content" / "lighting_pack"
TAGS_ROOT = PACK_ROOT / "tags"
JS_TREE = Path(__file__).resolve().parents[1] / "egodary" / "web" / "static" / "js" / "lighting-tree-data.js"
JS_PRESETS = Path(__file__).resolve().parents[1] / "egodary" / "web" / "static" / "js" / "lighting-presets-data.js"

# Camera labels for cross-category presets (must match catalog_camera_data.py)
CAMERA_PRESET_LABELS: dict[str, str] = {
    "angle": "catalog_camera_data",
    "framing": "catalog_camera_data",
}


def slug(label: str) -> str:
    return (
        label.lower()
        .replace("(", "")
        .replace(")", "")
        .replace("'", "")
        .replace('"', "")
        .replace("/", " ")
        .replace("+", " ")
        .replace("&", " ")
        .replace("-", " ")
        .replace(",", "")
        .replace("–", " ")
        .replace("—", " ")
        .replace("  ", " ")
        .strip()
        .replace(" ", "_")
    )


def lighting_item(label: str, subgroup: str) -> dict:
    ill = label.lower()
    return {
        "id": slug(label),
        "label": label,
        "meta": {"subgroup": subgroup},
        "tags": {
            "illustrious": ill,
            "anima": f"{ill}, cinematic lighting",
            "zimage_turbo": f"with {ill}",
        },
    }


def items_from_groups(groups: dict[str, list[str]]) -> list[dict]:
    items: list[dict] = []
    used: set[str] = set()
    for subgroup, labels in groups.items():
        for label in labels:
            item_id = slug(label)
            if item_id in used:
                item_id = f"{subgroup}_{item_id}"
            used.add(item_id)
            item = lighting_item(label, subgroup)
            item["id"] = item_id
            items.append(item)
    return items


def write_category(field: str, items: list[dict]) -> None:
    cat_id = f"lighting.{field}"
    title = LIGHTING_FIELD_LABELS.get(field, field.replace("_", " ").title())
    path = TAGS_ROOT / f"{field}.yaml"
    payload = {"id": cat_id, "title": title, "items": items}
    path.write_text(yaml.dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")


def write_lighting_tree_js() -> None:
    tree: list[dict] = []
    for field, groups in LIGHTING_CATALOG.items():
        labels = LIGHTING_SUBGROUP_LABELS.get(field, {})
        children = []
        for subgroup in groups:
            children.append(
                {
                    "id": f"lighting_{field}_{subgroup}",
                    "label": labels.get(subgroup, subgroup.replace("_", " ").title()),
                    "field": field,
                    "categoryId": f"lighting.{field}",
                    "subgroup": subgroup,
                }
            )
        tree.append(
            {
                "id": f"lighting_{field}",
                "label": LIGHTING_FIELD_LABELS.get(field, field.replace("_", " ").title()),
                "children": children,
            }
        )
    JS_TREE.parent.mkdir(parents=True, exist_ok=True)
    JS_TREE.write_text(
        f"/* Auto-generated by build_lighting_catalog.py */\nwindow.LIGHTING_TREE = {json.dumps(tree, indent=2)};\n",
        encoding="utf-8",
    )


def _load_camera_label_index() -> dict[str, dict[str, str]]:
    from catalog_camera_data import CAMERA_CATALOG

    index: dict[str, dict[str, str]] = {"angle": {}, "framing": {}}
    for field in ("angle", "framing"):
        used: set[str] = set()
        for subgroup, labels in CAMERA_CATALOG.get(field, {}).items():
            for label in labels:
                item_id = slug(label)
                if item_id in used:
                    item_id = f"{subgroup}_{item_id}"
                used.add(item_id)
                index[field][label] = item_id
    return index


def write_presets_js(label_index: dict[str, dict[str, str]]) -> None:
    camera_index = _load_camera_label_index()
    presets: list[dict] = []
    lighting_fields = ("light_type", "direction", "quality", "color_mood", "nsfw")
    camera_fields = ("angle", "framing")

    for raw in LIGHTING_PRESETS:
        entry = {
            "id": raw["id"],
            "label": raw["label"],
            "hint": raw.get("hint", ""),
            "lighting": {},
            "camera": {},
        }
        for field in lighting_fields:
            if field in raw:
                entry["lighting"][field] = label_index[field][raw[field]]
        for field in camera_fields:
            if field in raw:
                entry["camera"][field] = camera_index[field][raw[field]]
        presets.append(entry)

    JS_PRESETS.write_text(
        f"/* Auto-generated by build_lighting_catalog.py */\n"
        f"window.LIGHTING_PRESETS = {json.dumps(presets, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )


def _resolve_rule_ids(rule: dict, label_index: dict[str, dict[str, str]], key: str, field: str) -> None:
    labels_key = f"{field}_labels"
    if labels_key in rule:
        rule[f"{field}_ids"] = [label_index[field][lb] for lb in rule.pop(labels_key)]


def write_rules_yaml(label_index: dict[str, dict[str, str]]) -> None:
    warnings: list[dict] = []
    field_map = {
        "light_type": "light_type",
        "direction": "direction",
        "quality": "quality",
        "color_mood": "color_mood",
        "nsfw": "nsfw",
    }
    for rule in LIGHTING_COMPAT_WARNINGS:
        entry = {"message": rule["message"]}
        raw = dict(rule)
        for prefix, field in field_map.items():
            labels_key = f"{prefix}_labels"
            if labels_key in raw:
                entry[f"{field}_ids"] = [label_index[field][lb] for lb in raw[labels_key]]
        warnings.append(entry)

    payload = {
        "compatibility_warnings": warnings,
        "single_select_fields": ["light_type", "direction", "quality", "color_mood", "nsfw"],
    }
    (PACK_ROOT / "lighting_rules.yaml").write_text(
        yaml.dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def main() -> None:
    TAGS_ROOT.mkdir(parents=True, exist_ok=True)
    label_index: dict[str, dict[str, str]] = {field: {} for field in LIGHTING_CATALOG}
    total = 0

    for field, groups in LIGHTING_CATALOG.items():
        items = items_from_groups(groups)
        for item in items:
            label_index[field][item["label"]] = item["id"]
        write_category(field, items)
        total += len(items)

    write_lighting_tree_js()
    write_presets_js(label_index)
    write_rules_yaml(label_index)
    print(f"Wrote {total} lighting tags across {len(LIGHTING_CATALOG)} categories to {TAGS_ROOT}")


if __name__ == "__main__":
    main()
