"""Generate tag-tooltips-ru.js from content YAML catalogs."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from label_ru import label_to_ru  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "egodary" / "content"
OUT = ROOT / "egodary" / "web" / "static" / "js" / "tag-tooltips-ru.js"


def collect_items() -> dict[str, str]:
    mapping: dict[str, str] = {}
    for path in sorted(CONTENT.rglob("tags/*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        category_id = data.get("id") or path.stem
        for item in data.get("items", []):
            item_id = item.get("id")
            if not item_id:
                continue
            label = item.get("label") or item_id
            meta = item.get("meta") or {}
            ru = meta.get("label_ru") or meta.get("tooltip_ru") or label_to_ru(label)
            mapping[f"{category_id}:{item_id}"] = ru
            mapping.setdefault(item_id, ru)
    return mapping


def main() -> None:
    mapping = collect_items()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* Auto-generated by build_tag_tooltips_ru.py — do not edit */\n"
        f"window.TAG_TOOLTIPS_RU = {json.dumps(mapping, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(mapping)} tooltip entries -> {OUT}")


if __name__ == "__main__":
    main()
