"""Face catalog subgroup definitions for face_pack tags."""

FACE_CATALOG: dict[str, dict[str, list[str]]] = {
    "facial_expression": {
        "seductive_teasing": [
            "Seductive bedroom eyes + slight smile",
            "Heavy-lidded eyes, parted lips",
            "Biting lower lip, looking up",
            "Slight smirk, half-lidded eyes",
            "Coy smile with head tilt",
            "Playful tongue between teeth",
            "Flirty wink + smile",
            "Looking down shyly but aroused",
            "Teasing pout",
            "Soft come here expression",
        ],
        "ahegao_extreme": [
            "Classic ahegao (tongue out, eyes rolled up)",
            "Light ahegao (half-lidded, tongue slightly out)",
            "Intense ahegao with tears",
            "Ahegao with heart-shaped pupils",
            "Broken ahegao (mind-broken expression)",
            "Ahegao with drooling",
            "Overstimulated ahegao",
            "Ahegao + blushing heavily",
            "Spiral eyes + open mouth",
            "Crossed eyes + tongue out",
        ],
        "orgasm_climax": [
            "Orgasm face (eyes squeezed shut, mouth open)",
            "Silent scream orgasm",
            "Shaking orgasm expression",
            "Ecstatic open-mouth moan",
            "Biting lip hard during orgasm",
            "Eyes rolled back in pleasure",
            "Face contorted in pleasure",
            "Afterglow soft smile + flushed cheeks",
            "Post-orgasm dazed expression",
            "Multiple orgasm face (overwhelmed)",
        ],
        "submissive_broken": [
            "Submissive / obedient look",
            "Broken / mind-broken expression",
            "Pleading eyes + open mouth",
            "Crying from pleasure (happy tears)",
            "Desperate / needy expression",
            "Please more face",
            "Defeated / conquered look",
            "Blushing + looking away embarrassed",
            "Teary eyes + parted lips",
            "Completely submissive, no resistance",
        ],
        "dominant_confident": [
            "Dominant smirk",
            "Confident seductive gaze",
            "Slight arrogant smile",
            "I own you expression",
            "Playful dominant",
            "Cold but aroused",
            "Commanding look",
        ],
        "other_erotic": [
            "Heavy breathing (mouth slightly open)",
            "Biting finger seductively",
            "Moaning face (eyes closed, mouth open)",
            "Shy but aroused",
            "Drunk on pleasure",
            "Pain + pleasure mix",
            "Pure lust expression",
            "Hypnotized / entranced look",
        ],
    },
    "mouth_lips": {
        "lip_shape_size": [
            "Full plump lips",
            "Extremely full bimbo lips",
            "Heart-shaped lips",
            "Wide mouth",
            "Small delicate lips",
            "Downturned lips",
            "Upturned lips (natural smile)",
            "Thin lips",
            "Very thick lower lip",
            "Asymmetrical lips",
        ],
        "lip_details_texture": [
            "Glossy wet lips",
            "Shiny plump lips",
            "Matte lips",
            "Slightly chapped lips (erotic)",
            "Lip gloss + drool",
            "Wet lips with saliva string",
            "Plump glossy lips",
            "Overlined lips",
            "Natural soft lips",
            "Metallic/shimmer lips",
        ],
        "mouth_expressions_static": [
            "Slightly parted lips",
            "Mouth open in moan",
            "Mouth open with tongue visible",
            "Biting lower lip",
            "Tongue slightly out",
            "Tongue fully out (ahegao style)",
            "Lips pursed",
            "Smiling with teeth",
            "Soft smile",
            "Pouty lips",
        ],
    },
    "eyes": {
        "eye_shape": [
            "Almond shaped eyes",
            "Round big eyes",
            "Hooded eyes",
            "Upturned eyes (fox eyes)",
            "Downturned eyes",
            "Wide doe eyes",
            "Narrow seductive eyes",
            "Cat-like eyes",
            "Big anime-style eyes",
            "Half-closed seductive eyes",
        ],
        "eye_size_details": [
            "Large expressive eyes",
            "Small sharp eyes",
            "Big sparkling eyes",
            "Heavy-lidded bedroom eyes",
            "Wide innocent eyes",
            "Narrow calculating eyes",
        ],
        "iris_pupil": [
            "Detailed realistic iris",
            "Heart-shaped pupils",
            "Spiral/hypnotic pupils",
            "Dilated pupils (aroused)",
            "Glowing eyes",
            "Glossy wet eyes",
            "Teary eyes",
            "Reddened eyes (crying from pleasure)",
        ],
        "eyelashes_eyeliner": [
            "Long thick eyelashes",
            "Dramatic winged eyeliner",
            "Heavy smokey eye makeup",
            "Natural eyelashes",
            "False lashes",
            "Wet clumpy lashes (from tears/drool)",
            "Lower lash line emphasis",
        ],
    },
    "eye_color": {
        "natural": [
            "Blue",
            "Light Blue",
            "Deep Blue",
            "Green",
            "Hazel",
            "Light Brown",
            "Dark Brown",
            "Black",
            "Gray",
            "Silver Gray",
            "Violet / Purple",
            "Red",
            "Amber / Golden",
            "Heterochromia (different colors)",
        ],
        "fantasy_glowing": [
            "Glowing Blue",
            "Glowing Cyan",
            "Glowing Green",
            "Glowing Purple",
            "Glowing Red",
            "Glowing Gold",
            "Glowing Pink",
            "Glowing White",
            "Neon Blue",
            "Neon Pink",
            "Neon Green",
        ],
    },
    "face_shape": {
        "basic_shapes": [
            "Oval face",
            "Round face",
            "Square face",
            "Heart-shaped face",
            "Diamond face",
            "Long rectangular face",
            "Triangle face",
            "Inverted triangle face",
        ],
        "feminine_attractive": [
            "Soft heart-shaped face",
            "Delicate oval face",
            "V-shaped face (sharp jaw + wide forehead)",
            "Soft round face (bimbo style)",
            "Symmetrical perfect oval",
            "Slightly elongated face",
            "Youthful round face",
            "Mature elegant oval",
        ],
        "fetish_stylized": [
            "Extreme bimbo face (very soft, round, small chin)",
            "Doll-like face",
            "Cat-like face (sharp features)",
            "Babyface (very youthful)",
            "Sharp model face",
            "Soft submissive face",
            "Angular dominant face",
            "Ethereal / alien-like face",
        ],
    },
    "eyebrows": {
        "shape": [
            "Straight eyebrows",
            "Soft arched eyebrows",
            "High arched eyebrows",
            "Low set eyebrows",
            "Rounded eyebrows",
            "Angular sharp eyebrows",
            "S-shaped eyebrows",
            "Flat eyebrows",
        ],
        "thickness_style": [
            "Thin elegant eyebrows",
            "Medium natural eyebrows",
            "Thick full eyebrows",
            "Very thin arched (bimbo/classic)",
            "Fluffy thick eyebrows",
            "Microbladed sharp eyebrows",
            "Natural messy eyebrows",
            "Perfectly groomed thin brows",
        ],
        "position_expression": [
            "Neutral position",
            "Slightly raised (surprised/aroused)",
            "Furrowed (intense/angry pleasure)",
            "Relaxed soft position",
            "One eyebrow raised (teasing)",
            "Low and seductive",
            "High and innocent",
        ],
    },
    "nose": {
        "shape": [
            "Small delicate nose",
            "Button nose",
            "Straight nose",
            "Slightly upturned nose",
            "Aquiline nose",
            "Wide nose",
            "Narrow refined nose",
            "Snub nose",
        ],
        "details": [
            "Small cute nose",
            "Perfect straight nose",
            "Slightly wide nostrils",
            "Narrow elegant nose",
            "Soft rounded tip",
            "Sharp defined nose",
            "Subtle nose bump",
            "Very small nose (doll-like)",
        ],
        "nsfw_variants": [
            "Cute small nose (bimbo)",
            "Slightly red nose (aroused/crying)",
            "Wet/glossy nose tip",
            "Nose with light freckles",
            "Delicate feminine nose",
        ],
    },
    "jaw_chin": {
        "jawline": [
            "Soft rounded jawline",
            "Sharp defined jawline",
            "Soft feminine jaw",
            "Strong angular jaw",
            "Weak/soft jaw (bimbo style)",
            "Heart-shaped jawline",
            "Square soft jaw",
            "Delicate narrow jaw",
        ],
        "chin": [
            "Small delicate chin",
            "Pointed chin",
            "Rounded soft chin",
            "Slightly recessed chin",
            "Prominent chin",
            "Cleft chin (subtle)",
            "Very small chin (extreme bimbo)",
            "Double chin (soft, cute)",
        ],
        "combinations": [
            "Soft jaw + small chin (bimbo)",
            "Sharp jaw + pointed chin (model)",
            "Soft everything (cute/submissive)",
            "Strong jaw + soft chin (dominant feminine)",
        ],
    },
    "age_maturity": {
        "young_adult": [
            "Fresh 18-20 years old",
            "Young college girl look",
            "Innocent youthful face",
            "Early 20s fresh face",
            "Barely legal appearance",
        ],
        "mature_milf": [
            "Mature beautiful woman (28-35)",
            "MILF face",
            "Elegant mature beauty",
            "Sophisticated 30+",
            "Experienced seductive look",
        ],
        "ageless_stylized": [
            "Ageless beauty",
            "Doll-like timeless face",
            "Ethereal beauty",
            "Fantasy race appearance (elf, succubus, etc.)",
            "Perfect ageless skin",
        ],
        "specific_vibes": [
            "Cute & youthful",
            "Seductive mature",
            "Innocent but corrupted",
            "Broken-in / used look",
            "Fresh and untouched",
        ],
    },
    "beauty_archetype": {
        "classic_elegant": [
            "Classic beauty",
            "Elegant refined beauty",
            "Timeless beauty",
            "Sophisticated beauty",
            "Model beauty",
        ],
        "cute_innocent": [
            "Cute girl next door",
            "Innocent beauty",
            "Adorable / kawaii",
            "Sweet and pure",
            "Shy cute type",
        ],
        "fetish_extreme": [
            "Bimbo beauty",
            "Doll-like beauty",
            "Hyper feminine",
            "Succubus / demonic beauty",
            "Broken beauty",
            "Corrupted innocent",
            "Mind-broken beauty",
        ],
        "seductive_erotic": [
            "Seductive vixen",
            "Femme fatale",
            "Bedroom eyes beauty",
            "Pure lust appearance",
            "Erotic goddess",
            "Submissive beauty",
            "Dominant beauty",
        ],
        "exotic_unique": [
            "Exotic beauty",
            "Mixed ethnicity beauty",
            "Ethereal / otherworldly",
            "Dark feminine beauty",
            "Unique striking beauty",
        ],
    },
    "facial_details": {
        "positive_attractive": [
            "Cute dimples",
            "Light freckles on cheeks and nose",
            "Beauty mark above lip",
            "Subtle blush",
            "Natural glow",
        ],
        "erotic_nsfw": [
            "Heavy blush (aroused)",
            "Tear streaks on cheeks",
            "Saliva on lips and chin",
            "Flushed face and ears",
            "Sweat on forehead and upper lip",
            "Red bitten lips",
            "Smudged makeup (after intense activity)",
            "Glossy wet skin on face",
        ],
    },
}

# Subgroup display labels for the Face UI tree (generated alongside catalog).
FACE_SUBGROUP_LABELS: dict[str, dict[str, str]] = {
    "facial_expression": {
        "seductive_teasing": "Seductive & Teasing",
        "ahegao_extreme": "Ahegao & Extreme Pleasure",
        "orgasm_climax": "Orgasm / Climax",
        "submissive_broken": "Submissive / Broken",
        "dominant_confident": "Dominant / Confident",
        "other_erotic": "Other Erotic",
    },
    "mouth_lips": {
        "lip_shape_size": "Lip Shape & Size",
        "lip_details_texture": "Lip Details & Texture",
        "mouth_expressions_static": "Mouth Expressions",
    },
    "eyes": {
        "eye_shape": "Eye Shape",
        "eye_size_details": "Eye Size & Details",
        "iris_pupil": "Iris & Pupil",
        "eyelashes_eyeliner": "Eyelashes & Eyeliner",
    },
    "eye_color": {
        "natural": "Eye Color",
        "fantasy_glowing": "Fantasy / Sci-Fi Eye Colors",
    },
    "face_shape": {
        "basic_shapes": "Basic Shapes",
        "feminine_attractive": "Feminine & Attractive",
        "fetish_stylized": "Fetish / Stylized",
    },
    "eyebrows": {
        "shape": "Shape",
        "thickness_style": "Thickness & Style",
        "position_expression": "Position & Expression",
    },
    "nose": {
        "shape": "Shape",
        "details": "Details",
        "nsfw_variants": "NSFW Variants",
    },
    "jaw_chin": {
        "jawline": "Jawline",
        "chin": "Chin",
        "combinations": "Combinations",
    },
    "age_maturity": {
        "young_adult": "Young Adult (18–25)",
        "mature_milf": "Mature / MILF",
        "ageless_stylized": "Ageless / Stylized",
        "specific_vibes": "Specific Vibes",
    },
    "beauty_archetype": {
        "classic_elegant": "Classic & Elegant",
        "cute_innocent": "Cute & Innocent",
        "fetish_extreme": "Fetish / Extreme",
        "seductive_erotic": "Seductive & Erotic",
        "exotic_unique": "Exotic & Unique",
    },
    "facial_details": {
        "positive_attractive": "Positive / Attractive",
        "erotic_nsfw": "Erotic / NSFW",
    },
}

FACE_FIELD_LABELS: dict[str, str] = {
    "facial_expression": "Facial Expression",
    "mouth_lips": "Mouth & Lips",
    "eyes": "Eyes",
    "eye_color": "Eye Color",
    "skin": "Skin",
    "face_shape": "Face Shape",
    "eyebrows": "Eyebrows",
    "nose": "Nose",
    "jaw_chin": "Jaw & Chin",
    "age_maturity": "Age & Maturity",
    "beauty_archetype": "Beauty Archetype",
    "facial_details": "Facial Details",
}
