"""NSFW catalog subgroup definitions for outfit and appearance packs."""

DRESS_GROUPS: dict[str, list[str]] = {
    "micro_mini": [
        "Micro Mini Dress",
        "Pleated Micro Dress",
        "Latex Micro Dress",
        "Vinyl Micro Dress",
        "Sheer Micro Dress",
        "Bodycon Micro Dress",
        "High Slit Micro Dress",
        "Strappy Micro Dress",
        "Wetlook Micro Dress",
        "Cutout Micro Dress",
        "Harness Micro Dress",
        "See-Through Micro Dress",
    ],
    "sheer": [
        "Sheer Mesh Dress",
        "See-Through Long Dress",
        "Lace Sheer Dress",
        "Transparent Vinyl Dress",
        "Sheer High Slit Dress",
        "Fishnet Overlay Dress",
        "Sheer Wetlook Dress",
        "Completely See-Through Mini",
        "Sheer Backless Dress",
        "Sheer Cutout Dress",
    ],
    "latex_vinyl": [
        "Tight Latex Mini Dress",
        "Glossy Vinyl Dress",
        "Black Latex Long Dress",
        "Red Latex Mini Dress",
        "Wetlook Vinyl Mini",
        "Latex High Slit Dress",
        "Shiny Vinyl Bodycon",
        "Latex Cutout Dress",
        "Vinyl Strappy Dress",
        "Latex Harness Dress",
    ],
    "high_slit_cutout": [
        "Extreme High Slit Dress",
        "Side Cutout Dress",
        "Deep Cleavage Cutout",
        "Backless High Slit",
        "Waist Cutout Dress",
        "Multiple Cutouts Dress",
        "Slit to Hip Dress",
        "Keyhole Cutout Dress",
        "Underboob Cutout Dress",
        "Asymmetric Cutout Dress",
    ],
    "bodysuit_harness": [
        "Strappy Harness Bodysuit Dress",
        "Latex Bodysuit Dress",
        "Open Front Bodysuit Dress",
        "Crotchless Bodysuit Dress",
        "Bondage Harness Dress",
        "Sheer Bodysuit Dress",
        "Vinyl Cutout Bodysuit",
        "Full Body Harness Dress",
    ],
}

TOP_GROUPS: dict[str, list[str]] = {
    "harness_strappy": [
        "Black Harness Top",
        "Strappy Cage Top",
        "Bondage Harness Bra",
        "Multiple Strap Top",
        "Underboob Harness",
        "Chest Harness Top",
        "Strappy Bralette",
        "Open Cup Harness",
        "Full Body Harness Top",
        "Minimal Strap Top",
    ],
    "sheer_crop": [
        "Sheer Mesh Crop Top",
        "See-Through Long Sleeve Crop",
        "Lace Sheer Crop",
        "Transparent Vinyl Crop",
        "Fishnet Crop Top",
        "Sheer Off-Shoulder Crop",
        "Wetlook Sheer Crop",
        "Completely Transparent Crop",
    ],
    "bodysuits": [
        "Latex Bodysuit",
        "Strappy Bodysuit",
        "High Cut Leotard",
        "Crotchless Bodysuit",
        "Vinyl Bodysuit",
        "Sheer Bodysuit",
        "Harness Bodysuit",
        "Open Front Bodysuit",
    ],
    "latex_vinyl": [
        "Tight Latex Crop Top",
        "Glossy Vinyl Long Sleeve",
        "Latex Off-Shoulder Top",
        "Vinyl Underboob Top",
        "Latex Turtleneck Crop",
        "Shiny Wetlook Top",
        "Latex Keyhole Top",
        "Vinyl Strappy Crop",
    ],
    "micro_extreme": [
        "Extreme Micro Crop",
        "Underboob Only Top",
        "Nipple Pasties + Straps",
        "Micro Bandeau",
        "Slingshot Top",
        "Minimal Tape Top",
    ],
    "transparent_sheer_tops": [
        "Transparent White Shirt",
        "Sheer Button-Up Shirt",
        "See-Through Blouse",
        "Wet Transparent Shirt",
        "Transparent School Shirt",
        "Sheer Office Shirt",
        "Transparent Crop Top",
        "Clear Plastic Crop Top",
        "Neon Transparent Crop Top",
        "Sheer Long Sleeve Crop Top",
        "Sheer Turtleneck",
        "Transparent Tank Top",
        "See-Through Camisole",
        "Sheer Off-Shoulder Top",
        "Transparent Halter Top",
        "Wet See-Through T-Shirt",
        "Sheer Mesh Long Sleeve Top",
        "Transparent Vinyl Top",
        "Sheer Lace Top",
    ],
}

JACKET_GROUPS: dict[str, list[str]] = {
    "cropped": [
        "Cropped Denim Jacket",
        "Cropped Leather Jacket",
        "Cropped Latex Jacket",
        "Cropped Vinyl Jacket",
        "Cropped Biker Jacket",
        "Cropped Harness Jacket",
        "Cropped Bolero Jacket",
        "Cropped Open Front Jacket",
    ],
    "long_dramatic": [
        "Long Leather Coat",
        "Long Latex Coat",
        "Dramatic Cape Jacket",
        "Long Vinyl Trench",
        "Floor Length Leather",
        "Long Sheer Coat",
        "Long Wetlook Coat",
        "Long Harness Coat",
    ],
    "leather_latex_fetish": [
        "Shiny Black Leather Jacket",
        "Red Latex Jacket",
        "Vinyl Biker Jacket",
        "Wetlook Leather Jacket",
        "Strappy Leather Jacket",
        "Harness Detail Jacket",
        "Open Front Latex Jacket",
        "Bondage Style Jacket",
    ],
    "sheer_revealing": [
        "Sheer Mesh Jacket",
        "See-Through Vinyl Jacket",
        "Lace Long Jacket",
        "Fishnet Outer Layer",
        "Transparent Raincoat Style",
        "Sheer Open Jacket",
    ],
}

FOOTWEAR_GROUPS: dict[str, list[str]] = {
    "thigh_high": [
        "Thigh High Platform Boots",
        "Latex Thigh High Boots",
        "Vinyl Thigh High Boots",
        "Strappy Thigh High Boots",
        "Wetlook Thigh Highs",
        "Harness Detail Thigh Highs",
        "Over-the-Knee Platform",
        "Lace-Up Thigh High Boots",
        "Glossy Black Thigh Highs",
        "Extreme Platform Thigh Highs",
    ],
    "platform_heels": [
        "Extreme Platform Heels",
        "Strappy Platform Sandals",
        "Latex High Heels",
        "Vinyl Stilettos",
        "Clear Platform Heels",
        "Strappy Bondage Heels",
        "Wetlook Platform Pumps",
        "Open Toe Platform Heels",
    ],
    "fetish_boots": [
        "Combat Platform Boots",
        "Biker Latex Boots",
        "Knee High Vinyl Boots",
        "Strappy Ankle Boots",
        "Harness Ankle Boots",
        "Wetlook Combat Boots",
        "Buckle Detail Boots",
        "Extreme Heel Combat Boots",
        "Neon Platform Boots",
    ],
    "casual_nsfw": [
        "Chunky Platform Sneakers",
        "High Top Latex Sneakers",
        "Strappy Sandals",
        "Micro Mini Heel Slides",
        "Wetlook Trainers",
        "Open Toe Strappy Flats",
        "Neon Accent Sneakers",
    ],
}

GLOVES_GROUPS: dict[str, list[str]] = {
    "long_opera": [
        "Long Latex Opera Gloves",
        "Vinyl Long Gloves",
        "Sheer Long Gloves",
        "Wetlook Opera Gloves",
        "Harness Long Gloves",
        "Strappy Long Gloves",
        "Lace Long Opera Gloves",
        "Glossy Black Opera Gloves",
    ],
    "short_fashion": [
        "Short Latex Gloves",
        "Vinyl Short Gloves",
        "Leather Driving Gloves",
        "Sheer Wrist Gloves",
        "Wetlook Short Gloves",
        "Strappy Short Gloves",
    ],
    "harness_bondage": [
        "Full Hand Harness Gloves",
        "Strappy Fingerless Gloves",
        "Bondage Mittens",
        "Open Finger Harness Gloves",
        "Multiple Strap Gloves",
        "Cage Style Gloves",
    ],
    "fingerless_alt": [
        "Long Fingerless Gloves",
        "Arm Warmer Harness",
        "Studded Fingerless",
        "Mesh Fingerless Long",
        "Latex Fingerless Opera",
        "Tactical Strappy Hybrid Gloves",
    ],
}

CAPE_GROUPS: dict[str, list[str]] = {
    "long_dramatic": [
        "Long Flowing Cape",
        "Latex Long Cape",
        "Vinyl Dramatic Cape",
        "Sheer Long Cape",
        "Wetlook Long Cape",
        "Harness Detail Cape",
        "Open Front Long Cape",
        "Floor Length Cape",
    ],
    "short_cropped": [
        "Short Capelet",
        "Cropped Harness Cape",
        "Micro Cape",
        "Bolero Cape",
        "Short Sheer Capelet",
        "Vinyl Short Cape",
    ],
    "hooded_fetish": [
        "Hooded Latex Cape",
        "Hooded Vinyl Cape",
        "Sheer Hooded Cape",
        "Harness Hooded Cape",
        "Wetlook Hooded Cape",
        "Bondage Hooded Cape",
        "Strappy Hooded Cape",
        "Open Hooded Cape",
    ],
    "sheer_revealing": [
        "Completely Sheer Cape",
        "See-Through Mesh Cape",
        "Lace Cape",
        "Fishnet Cape",
        "Transparent Vinyl Cape",
        "Wet Sheer Cape",
    ],
}

HAIR_GROUPS: dict[str, list[str]] = {
    "long": [
        "Long Straight Wetlook",
        "Long Wavy Voluminous",
        "Long Curly Wild",
        "Long with Heavy Bangs",
        "Long Slicked Back Wet",
        "Long with Face Framing",
        "Long Ponytail High",
        "Long Half-Up",
    ],
    "updos_buns": [
        "High Messy Bun",
        "Sleek Low Bun",
        "Space Buns",
        "Top Knot Wetlook",
        "Braided Crown",
        "Loose Low Bun",
    ],
    "braids_ponytails": [
        "Double Dutch Braids",
        "High Ponytail",
        "Low Braided Ponytail",
        "Multiple Small Braids",
        "Fishtail Braid",
        "Pigtails Sexy",
    ],
    "short_alt": [
        "Pixie with Texture",
        "Short Shaggy Wetlook",
        "Bob with Heavy Bangs",
        "Undercut Long Top",
        "Slicked Back Short",
        "Messy Short Crop",
    ],
}

HAIR_COLOR_GROUPS: dict[str, list[str]] = {
    "hair_color": [
        "Platinum Blonde",
        "Golden Blonde",
        "Ash Blonde",
        "Light Brown",
        "Dark Brown",
        "Black",
        "Jet Black",
        "Auburn",
        "Copper Red",
        "Bright Red",
        "Burgundy",
        "Silver / Gray",
        "White",
        "Pastel Pink",
        "Pastel Blue",
        "Pastel Purple",
        "Mint Green",
        "Neon Pink",
        "Neon Blue",
        "Neon Green",
        "Rainbow / Multicolor",
        "Oil Slick (переливающийся)",
        "Metallic Silver",
        "Metallic Gold",
    ],
}

MAKEUP_GROUPS: dict[str, list[str]] = {
    "eyes": [
        "Heavy Smokey Eyes",
        "Glossy Black Smokey",
        "Winged + Glitter",
        "Graphic Eyeliner",
        "Cat Eye Extreme",
        "Wetlook Glossy Eyes",
        "Neon Cyber Eyes",
        "Heavy Lower Lash",
    ],
    "lips": [
        "Glossy Bold Red",
        "Glossy Black Lips",
        "Metallic Lips",
        "Wetlook Nude Gloss",
        "Overlined Glossy",
        "Ombre Glossy Lips",
    ],
    "full_face": [
        "Full Glam Heavy",
        "Gothic Pale + Dark Lips",
        "Dewy + Glossy Skin",
        "Matte + Bold Contour",
        "Cyberpunk Neon",
        "Wet Skin Look",
        "Extreme Blush + Gloss",
        "Monochrome Black & Silver",
    ],
}

ACCESSORIES_GROUPS: dict[str, list[str]] = {
    "body_jewelry": [
        "Full Body Chain Harness",
        "Strappy Body Harness",
        "Nipple Chains",
        "Waist Chain Harness",
        "Multiple Body Chains",
        "O-Ring Body Harness",
        "Strappy Chest Harness",
        "Bondage Body Jewelry",
    ],
    "belts_waist": [
        "Wide Harness Belt",
        "Multiple Strap Belt",
        "O-Ring Waist Harness",
        "Chain Waist Belt",
        "Vinyl Corset Belt",
        "Strappy Low Waist Belt",
    ],
    "headwear": [
        "Fedora Sexy Tilt",
        "Beanie Wetlook",
        "Baseball Cap Backward",
        "Harness Headpiece",
        "Latex Hood Partial",
        "Strappy Head Harness",
    ],
    "chokers_neck": [
        "O-Ring Choker",
        "Strappy Harness Choker",
        "Wide Leather Choker",
        "Chain Choker with Pendant",
        "Latex Collar",
        "Multiple Layer Chokers",
    ],
    "bags_extra": [
        "Small Chain Handbag",
        "Crossbody Harness Bag",
        "Mini Vinyl Purse",
        "Body Chain Bag",
        "Fetish Style Pouch",
    ],
    "backpacks": [
        "Strappy Backpack",
        "Heart-Shaped Backpack",
        "Cute Mini Backpack",
        "Transparent Backpack",
        "Neon Backpack",
        "Plastic Heart Bag",
        "Kawaii Backpack",
        "Crossbody Backpack",
        "Small Heart-Shaped Bag",
        "Neon Pink Backpack",
        "Utility Neon Backpack",
    ],
}

DRESS_LAYER_SUBGROUPS = ("micro_mini", "sheer", "bodysuit_harness")
LAYERABLE_BOTTOM_SUBGROUPS = ("skirts", "shorts", "transparent_plastic_skirts")

BULKY_JACKET_IDS = [
    "long_leather_coat",
    "long_latex_coat",
    "floor_length_leather",
    "long_vinyl_trench",
    "dramatic_cape_jacket",
]

LONG_CAPE_IDS = [
    "long_flowing_cape",
    "latex_long_cape",
    "floor_length_cape",
    "open_front_long_cape",
    "wetlook_long_cape",
]

BOTTOM_GROUPS: dict[str, list[str]] = {
    "long_pants": [
        "Skinny Jeans",
        "Shiny Leather Pants",
        "Tight Latex Pants",
        "Glossy Vinyl Pants",
        "High-Waisted Trousers",
        "Low-Rise Skinny Pants",
        "Sexy Cargo Pants",
        "Wide Leg Leather Pants",
        "Flared Latex Pants",
        "Slim Fit Vinyl Trousers",
        "Shiny Leggings",
        "High-Waisted Jeggings",
        "Leather Leggings",
        "Latex Leggings",
        "Bootcut Leather Pants",
        "Sheer Mesh Over Pants",
        "Strappy Harness Pants",
        "High-Waisted Vinyl Pants",
        "Pleated Leather Trousers",
        "Wetlook Leggings",
    ],
    "skirts": [
        "Micro Mini Skirt",
        "Pleated Micro Skirt",
        "Leather Micro Mini",
        "Latex Mini Skirt",
        "Denim Micro Skirt",
        "High Slit Pencil Skirt",
        "Wrap Micro Skirt",
        "Pleated Schoolgirl Micro",
        "Vinyl Micro Skirt",
        "Sheer See-Through Mini",
        "Asymmetrical Micro Skirt",
        "Cargo Micro Skirt",
        "Leather Pencil Skirt",
        "Extreme High Slit Maxi",
        "Tiered Micro Skirt",
        "Bodycon Micro Skirt",
        "Fishnet Overlay Skirt",
        "Strappy Micro Skirt",
        "Latex High Slit Skirt",
        "Bondage Strap Skirt",
        "Sheer Mini Skirt",
        "Transparent Vinyl Skirt",
        "PVC Micro Skirt",
    ],
    "transparent_plastic_skirts": [
        "Transparent Plastic Skirt",
        "Clear PVC Skirt",
        "Neon Transparent Skirt",
        "Glossy Transparent Mini Skirt",
        "Sheer Plastic Skirt",
        "Iridescent Transparent Skirt",
        "Neon Green Transparent Skirt",
        "Clear Vinyl Skirt",
        "See-Through Plastic Pleated Skirt",
        "Transparent Bubble Skirt",
        "Glossy Clear Mini Skirt",
        "Transparent Layered Skirt",
    ],
    "shorts": [
        "Micro Hotpants",
        "Denim Micro Shorts",
        "Leather Hotpants",
        "Latex Micro Shorts",
        "High-Cut Booty Shorts",
        "Vinyl Hotpants",
        "Sheer Mesh Shorts",
        "Strappy Harness Shorts",
        "Cargo Micro Shorts",
        "Dolphin Micro Shorts",
        "Pleated Micro Shorts",
        "High-Waisted Micro Shorts",
        "Cut-Off Denim Booty Shorts",
        "Ripped Micro Shorts",
        "Bondage Strap Shorts",
        "Wetlook Hotpants",
        "Extreme Micro Hotpants",
        "Fishnet Overlay Shorts",
        "Thong-Style Shorts",
        "Harness Micro Shorts",
    ],
    "underwear": [
        "Classic Lace Panties",
        "Classic Thong",
        "G-String",
        "Tanga",
        "Boyshorts",
        "Crotchless Panties",
        "Open Crotch Thong",
        "Strappy Harness Panties",
        "Latex Panties",
        "Vinyl Panties",
        "Sheer Mesh Panties",
        "High-Cut Brazilian",
        "Micro G-String",
        "Pearl Thong",
        "Crotchless Lace Panties",
        "Bondage Harness Bottom",
        "See-Through Crotchless",
        "Strappy Open Panties",
        "Wetlook Micro Panties",
        "Extreme Micro Thong",
    ],
}

LEGWEAR_GROUPS: dict[str, list[str]] = {
    "classic": [
        "Sheer Pantyhose",
        "Opaque Black Tights",
        "Classic Fishnet Tights",
        "Lace Top Thigh Highs",
        "Stay-Up Stockings",
        "Garter Belt + Stockings",
        "Fishnet with Garter",
        "Sheer Thigh High Stockings",
        "Shiny Pantyhose",
        "Latex Stockings",
        "Vinyl Thigh Highs",
        "Ripped Fishnets",
        "Patterned Sexy Tights",
        "Hold-Up Lace Stockings",
        "Cuban Heel Stockings",
        "Strappy Leg Harness",
        "Sheer Seamed Stockings",
        "Over-the-Knee Fishnets",
        "Bondage Strap Legwear",
        "Wetlook Thigh Highs",
    ],
    "neon_legwear": [
        "Neon Green Thigh-High Socks",
        "Neon Pink Thigh-High Socks",
        "Striped Neon Leg Warmers",
        "Neon Green and Black Thigh-Highs",
        "Bright Neon Knee-High Socks",
        "Neon Striped Thigh-Highs",
        "Glowing Neon Leg Warmers",
        "Neon Green Over-the-Knee Socks",
        "Two-Tone Neon Socks",
        "Neon Accent Thigh-Highs",
    ],
}

OUTFIT_NONE_ITEMS: dict[str, dict[str, object]] = {
    "dress": {
        "label": "None (no dress)",
        "tags": {
            "illustrious": "no dress",
            "anima": "no dress",
            "zimage_turbo": "without dress",
        },
    },
    "top": {
        "label": "None (no top)",
        "tags": {
            "illustrious": "topless, bare breasts, no top",
            "anima": "topless, bare breasts, no top",
            "zimage_turbo": "topless with bare breasts and no top",
        },
    },
    "bottom": {
        "label": "None (no bottom)",
        "tags": {
            "illustrious": "bottomless, no bottom garment",
            "anima": "bottomless, no bottom garment",
            "zimage_turbo": "bottomless with no bottom garment",
        },
    },
    "underwear_layer": {
        "label": "None (no underwear layer)",
        "tags": {
            "illustrious": "no underwear layer",
            "anima": "no underwear layer",
            "zimage_turbo": "without underwear layer",
        },
    },
    "legwear": {
        "label": "None (no legwear)",
        "tags": {
            "illustrious": "bare legs, no legwear",
            "anima": "bare legs, no legwear",
            "zimage_turbo": "with bare legs and no legwear",
        },
    },
    "jacket": {
        "label": "None (no jacket)",
        "tags": {
            "illustrious": "no jacket",
            "anima": "no jacket",
            "zimage_turbo": "without jacket",
        },
    },
    "footwear": {
        "label": "None (barefoot)",
        "tags": {
            "illustrious": "barefoot, no footwear",
            "anima": "barefoot, no footwear",
            "zimage_turbo": "barefoot with no footwear",
        },
    },
    "gloves": {
        "label": "None (no gloves)",
        "tags": {
            "illustrious": "bare hands, no gloves",
            "anima": "bare hands, no gloves",
            "zimage_turbo": "with bare hands and no gloves",
        },
    },
    "cape": {
        "label": "None (no cape)",
        "tags": {
            "illustrious": "no cape",
            "anima": "no cape",
            "zimage_turbo": "without cape",
        },
    },
}
