"""Pose catalog subgroup definitions."""

SOLO_GROUPS: dict[str, list[str]] = {
    "standing_seductive": [
        "Confident standing, hand on hip, chest forward",
        "Standing with legs slightly apart, intense eye contact",
        "Standing arching back, hands in hair",
        "Standing with one leg bent, hip pop strong",
        "Standing looking over shoulder (ass focus)",
        "Standing with arms raised behind head",
        "Standing chest out, shoulders back",
        "Standing with hands slowly sliding down body",
        "Standing with one hand on thigh, seductive gaze",
        "Standing with legs crossed, leaning slightly",
        "Standing powerful stance, looking down at viewer",
        "Standing teasing, biting lip",
    ],
    "standing_tease": [
        "Standing pulling micro skirt up slightly",
        "Standing holding cape/jacket open",
        "Standing bending forward slightly (cleavage/ass focus)",
        "Standing with legs wide, hands on knees",
        "Standing lifting one leg against wall",
        "Standing with hands spreading ass cheeks (over clothes)",
        "Standing adjusting harness/top teasingly",
        "Standing with back arched, ass pushed out",
        "Standing with fingers in mouth",
        "Standing pulling top down exposing more",
        "Standing with hand between legs (over clothes)",
        "Standing looking back while lifting skirt",
    ],
    "sitting_kneeling": [
        "Sitting on edge, legs spread wide",
        "Sitting with knees together, leaning forward (cleavage)",
        "Kneeling on floor, sitting on heels, looking up",
        "Sitting with one leg up, other spread",
        "Kneeling leaning back on hands, chest out",
        "Sitting with legs crossed high (thigh focus)",
        "Kneeling with hands on thighs, seductive",
        "Sitting low, knees apart, hands between legs",
        'Kneeling in "worship" pose, hands on floor',
        "Sitting sideways, looking over shoulder",
        "Kneeling with back arched",
        "Sitting with legs in M-position (very explicit)",
    ],
    "lying_bed": [
        "Lying on back, legs spread wide, knees bent",
        "Lying on side, one leg lifted high",
        "Lying on stomach, ass up slightly (prone bone hint)",
        "Lying on back, hands above head, back arched",
        "Lying with legs in air, holding ankles",
        "Lying on side, hand between legs",
        "Lying on back, knees to chest (very open)",
        "Lying on stomach, looking back at viewer",
        "Lying with one leg straight, other bent",
        'Lying in "butterfly" position',
        "Lying on back, hips raised (bridge pose)",
        "Lying on side, top leg bent over",
        "Lying with hands squeezing breasts",
        "Lying in fetal position but seductive",
    ],
    "all_fours": [
        "On all fours, back arched, looking back",
        "On all fours, ass high, chest low",
        "On all fours, legs spread wide",
        "On all fours, one hand reaching back",
        "On all fours, head down, ass up",
        "On all fours, looking at viewer over shoulder",
        "On all fours, slowly lowering chest",
        "On all fours, one leg lifted",
        "On all fours, hands pulling ass apart",
        'On all fours in "presenting" pose',
    ],
    "dynamic_action": [
        "Walking toward camera seductively",
        "Spinning / turning with hair/cape",
        "Bending over to pick something up",
        "Stretching with back arch",
        "Dancing / moving hips",
        "Leaning against wall, one leg up",
        "Crouching down slowly",
        "Standing up from kneeling pose",
        "Hair flip while bending",
        "Playful run / chase pose",
    ],
    "self_touch": [
        "Hand between legs, touching self",
        "Squeezing breasts with both hands",
        "Hand inside panties / harness",
        "Fingers in mouth while touching",
        "Both hands on body, exploring",
        "Touching nipples through clothes",
        "Hand sliding down stomach",
        "Gripping thighs while spreading",
        "Playing with hair while touching",
        "Intense eye contact while self-touching",
    ],
    "extreme_solo": [
        "Legs completely spread in split",
        "Bent over 90 degrees, hands on floor",
        "On back with legs behind head",
        "Squatting with knees wide open",
        "Lying with ass up, face down",
        "Standing split (one leg high on wall)",
        "Deep squat facing camera",
        "On all fours with extreme arch",
        "Lying with hips raised high",
        '"Ahegao" style face + body pose',
    ],
}

COUPLE_GROUPS: dict[str, list[str]] = {
    "standing_intimate": [
        "Standing hug from behind, hands on waist",
        "Standing face to face, foreheads touching",
        "Standing with partner behind, hands exploring",
        "Standing kiss with hands in hair",
        "Standing embrace, one leg wrapped around",
        "Standing with partner grabbing ass",
        "Standing back-to-chest, hands on breasts",
        "Standing slow dance pose",
        "Standing with partner lifting one leg",
        "Standing teasing kiss on neck",
    ],
    "kissing_foreplay": [
        "Deep passionate kiss, bodies pressed",
        "Kissing while hands under clothes",
        "Neck kissing while partner touches",
        "Making out against wall",
        "Kissing while grinding",
        "Partner kissing chest/breasts",
        "Slow sensual kissing with eye contact",
        "Biting lip during kiss",
        "Kissing while hands between legs",
        "Passionate embrace with roaming hands",
    ],
    "sexual_standing": [
        "Standing sex from behind (partner holding hips)",
        "Standing facing, one leg lifted",
        "Standing against wall sex",
        "Standing carry (partner holding thighs)",
        "Standing bent over sex",
        "Standing with one leg on partner's shoulder",
        "Standing grinding / dry humping",
        "Standing with partner inside from front",
        "Standing spooning position",
        "Standing with deep penetration angle",
        "Standing with hands pinned against wall",
        "Standing with partner lifting completely",
    ],
    "oral_foreplay": [
        "Kneeling giving oral (looking up)",
        "Partner performing oral while standing",
        "69 position (lying)",
        "Sitting on face",
        "Kneeling between partner's legs",
        "Bent over receiving oral from behind",
        "Lying with legs over partner's shoulders",
        "Sitting on edge receiving oral",
        "Standing receiving oral",
        "Mutual oral (side by side)",
    ],
    "penetration": [
        "Missionary (legs spread wide)",
        "Doggy style (ass up)",
        "Cowgirl / Riding (facing)",
        "Reverse Cowgirl",
        "Spooning sex",
        "Prone bone (lying flat)",
        "Legs over shoulders",
        "Mating press",
        "Standing split penetration",
        "Bent over table/desk",
        "Lotus position (sitting face to face)",
        "Piledriver (extreme)",
        "Side-lying scissors",
        "Deep missionary with legs folded",
    ],
    "tease_aftercare": [
        "Cuddling naked / semi-naked",
        "Spooning embrace",
        "Gentle touching after sex",
        "Kissing forehead / neck softly",
        "Lying together, hands intertwined",
        "Partner caressing body",
        "Playful teasing / tickling",
        "Afterglow pose (relaxed, satisfied)",
    ],
}
