"""Camera catalog subgroup definitions for camera_pack tags."""

CAMERA_FIELD_LABELS: dict[str, str] = {
    "angle": "Camera Angle",
    "framing": "Framing / Shot Type",
    "lens": "Focal Length",
    "focus": "Focus & Depth of Field",
    "composition": "Composition",
    "nsfw_shot": "NSFW-Specific Shots",
}

CAMERA_SUBGROUP_LABELS: dict[str, dict[str, str]] = {
    "angle": {
        "standard_angles": "Standard Angles",
        "extreme_dramatic": "Extreme & Dramatic",
        "nsfw_angles": "NSFW-oriented Angles",
    },
    "framing": {
        "close_intimate": "Close & Intimate",
        "medium_shots": "Medium Shots",
        "full_wide": "Full & Wide",
        "special_framing": "Special Framing",
    },
    "lens": {
        "focal_length": "Focal Length",
    },
    "focus": {
        "focus_dof": "Focus & DOF",
    },
    "composition": {
        "classic": "Classic Compositions",
        "cinematic": "Cinematic & Dramatic",
        "nsfw_composition": "NSFW / Erotic Composition",
    },
    "nsfw_shot": {
        "power_submission": "Power & Submission",
        "intimate_teasing": "Intimate & Teasing",
        "pov_immersive": "POV & Immersive",
        "dynamic_kinky": "Dynamic & Kinky",
    },
}

CAMERA_CATALOG: dict[str, dict[str, list[str]]] = {
    "angle": {
        "standard_angles": [
            "Eye Level",
            "Low Angle",
            "High Angle",
            "Dutch Angle",
        ],
        "extreme_dramatic": [
            "Extreme Low Angle",
            "Extreme High Angle",
            "Worm's Eye View",
            "Bird's Eye View",
            "Over the Shoulder",
            "POV (first person)",
        ],
        "nsfw_angles": [
            "Low Angle looking up (dominance)",
            "High Angle looking down (vulnerability)",
            "Low Angle from floor level",
            "High Angle from above (submission)",
            "Dutch Angle for tension",
        ],
    },
    "framing": {
        "close_intimate": [
            "Extreme Close-Up (face/eyes/lips)",
            "Close-Up",
            "Tight Close-Up",
            "Portrait",
        ],
        "medium_shots": [
            "Upper Body",
            "Cowboy Shot (thighs)",
            "Medium Shot",
        ],
        "full_wide": [
            "Full Body",
            "Full Body with space",
            "Wide Shot",
            "Extreme Wide Shot",
        ],
        "special_framing": [
            "Over the Shoulder Shot",
            "From Behind",
            "Mirror Reflection Shot",
            "Split Diopter / Two focus planes",
        ],
    },
    "lens": {
        "focal_length": [
            "24mm (wide angle)",
            "35mm",
            "50mm (standard)",
            "85mm (portrait)",
            "105mm",
            "135mm (strong compression)",
        ],
    },
    "focus": {
        "focus_dof": [
            "Shallow Depth of Field",
            "Deep Depth of Field",
            "Sharp focus on face",
            "Sharp focus on eyes",
            "Focus on lips",
            "Bokeh background",
            "Creamy bokeh",
            "Foreground blur",
            "Background blur (strong)",
        ],
    },
    "composition": {
        "classic": [
            "Rule of Thirds",
            "Centered composition",
            "Symmetrical composition",
            "Asymmetrical composition",
            "Leading lines",
            "Negative space",
        ],
        "cinematic": [
            "Cinematic composition",
            "Dramatic angle",
            "Low key composition",
            "High key composition",
            "Silhouette composition",
            "Rim lighting composition",
        ],
        "nsfw_composition": [
            "Focus on body curves",
            "Emphasis on legs / thighs",
            "Emphasis on chest",
            "Emphasis on ass (from behind)",
            "Intimate close framing",
        ],
    },
    "nsfw_shot": {
        "power_submission": [
            "Low angle dominance shot",
            "High angle submission shot",
            "Looking up from below",
            "Looking down from above",
        ],
        "intimate_teasing": [
            "Extreme close-up on lips",
            "Extreme close-up on eyes",
            "Close-up on neck and cleavage",
            "Focus on inner thighs",
            "Focus on ass (bent over)",
        ],
        "pov_immersive": [
            "POV (male gaze)",
            "POV from below",
            "Over the shoulder POV",
            "Mirror POV",
        ],
        "dynamic_kinky": [
            "Dutch angle erotic tension",
            "Low angle looking up skirt",
            "High angle on kneeling figure",
            "Bent over from behind framing",
            "Legs spread framing",
        ],
    },
}

# Preset definitions — labels resolved to item ids by build_camera_catalog.py
# Source: Camera_Presets_30.md (June 2026)
CAMERA_PRESETS: list[dict[str, str]] = [
    {
        "id": "camera_preset_01",
        "label": "Классический портрет",
        "hint": "Eye Level + Portrait + 85mm + Rule of Thirds",
        "angle": "Eye Level",
        "framing": "Portrait",
        "lens": "85mm (portrait)",
        "composition": "Rule of Thirds",
    },
    {
        "id": "camera_preset_02",
        "label": "Элегантный средний план",
        "hint": "Eye Level + Upper Body + 85mm + Centered composition",
        "angle": "Eye Level",
        "framing": "Upper Body",
        "lens": "85mm (portrait)",
        "composition": "Centered composition",
    },
    {
        "id": "camera_preset_03",
        "label": "Полный рост в пространстве",
        "hint": "Eye Level + Full Body with space + 35mm + Rule of Thirds",
        "angle": "Eye Level",
        "framing": "Full Body with space",
        "lens": "35mm",
        "composition": "Rule of Thirds",
    },
    {
        "id": "camera_preset_04",
        "label": "Кинематографичный средний план",
        "hint": "Eye Level + Medium Shot + 50mm + Cinematic composition",
        "angle": "Eye Level",
        "framing": "Medium Shot",
        "lens": "50mm (standard)",
        "composition": "Cinematic composition",
    },
    {
        "id": "camera_preset_05",
        "label": "Драматичный низкий ракурс",
        "hint": "Low Angle + Cowboy Shot + 35mm + Dramatic angle",
        "angle": "Low Angle",
        "framing": "Cowboy Shot (thighs)",
        "lens": "35mm",
        "composition": "Dramatic angle",
    },
    {
        "id": "camera_preset_06",
        "label": "Мягкий интимный портрет",
        "hint": "Eye Level + Close-Up + 85mm + Shallow Depth of Field",
        "angle": "Eye Level",
        "framing": "Close-Up",
        "lens": "85mm (portrait)",
        "focus": "Shallow Depth of Field",
    },
    {
        "id": "camera_preset_07",
        "label": "Широкий атмосферный кадр",
        "hint": "Eye Level + Wide Shot + 24mm + Leading lines",
        "angle": "Eye Level",
        "framing": "Wide Shot",
        "lens": "24mm (wide angle)",
        "composition": "Leading lines",
    },
    {
        "id": "camera_preset_08",
        "label": "Симметричный художественный план",
        "hint": "Eye Level + Medium Shot + 50mm + Symmetrical composition",
        "angle": "Eye Level",
        "framing": "Medium Shot",
        "lens": "50mm (standard)",
        "composition": "Symmetrical composition",
    },
    {
        "id": "camera_preset_09",
        "label": "Репортажный динамичный план",
        "hint": "Eye Level + Medium Shot + 35mm + Asymmetrical composition",
        "angle": "Eye Level",
        "framing": "Medium Shot",
        "lens": "35mm",
        "composition": "Asymmetrical composition",
    },
    {
        "id": "camera_preset_10",
        "label": "Вертикальный крупный план",
        "hint": "Eye Level + Tight Close-Up + 85mm + Centered composition",
        "angle": "Eye Level",
        "framing": "Tight Close-Up",
        "lens": "85mm (portrait)",
        "composition": "Centered composition",
    },
    {
        "id": "camera_preset_11",
        "label": "Силуэт и форма",
        "hint": "Low Angle + Full Body + 35mm + Silhouette composition",
        "angle": "Low Angle",
        "framing": "Full Body",
        "lens": "35mm",
        "composition": "Silhouette composition",
    },
    {
        "id": "camera_preset_12",
        "label": "Золотой час / атмосферный",
        "hint": "Eye Level + Full Body + 50mm + Rule of Thirds",
        "angle": "Eye Level",
        "framing": "Full Body",
        "lens": "50mm (standard)",
        "composition": "Rule of Thirds",
    },
    {
        "id": "camera_preset_13",
        "label": "Чистый средний план",
        "hint": "Eye Level + Medium Shot + 50mm + Rule of Thirds",
        "angle": "Eye Level",
        "framing": "Medium Shot",
        "lens": "50mm (standard)",
        "composition": "Rule of Thirds",
    },
    {
        "id": "camera_preset_14",
        "label": "Архитектурно-пространственный",
        "hint": "Eye Level + Wide Shot + 24mm + Leading lines",
        "angle": "Eye Level",
        "framing": "Wide Shot",
        "lens": "24mm (wide angle)",
        "composition": "Leading lines",
    },
    {
        "id": "camera_preset_15",
        "label": "Мягкий крупный план",
        "hint": "Eye Level + Close-Up + 85mm + Creamy bokeh",
        "angle": "Eye Level",
        "framing": "Close-Up",
        "lens": "85mm (portrait)",
        "focus": "Creamy bokeh",
    },
    {
        "id": "camera_preset_16",
        "label": "Властный взгляд снизу",
        "hint": "Extreme Low Angle + Upper Body + 50mm + Low angle dominance shot",
        "angle": "Extreme Low Angle",
        "framing": "Upper Body",
        "lens": "50mm (standard)",
        "nsfw_shot": "Low angle dominance shot",
    },
    {
        "id": "camera_preset_17",
        "label": "Уязвимость и подчинение",
        "hint": "High Angle + Medium Shot + 85mm + High angle submission shot",
        "angle": "High Angle",
        "framing": "Medium Shot",
        "lens": "85mm (portrait)",
        "nsfw_shot": "High angle submission shot",
    },
    {
        "id": "camera_preset_18",
        "label": "Прижата к стене",
        "hint": "Low Angle + Upper Body + 50mm",
        "angle": "Low Angle",
        "framing": "Upper Body",
        "lens": "50mm (standard)",
    },
    {
        "id": "camera_preset_19",
        "label": "Наклон вперёд (провокация)",
        "hint": "Low Angle + Upper Body + 85mm + Bent over framing + Emphasis on chest",
        "angle": "Low Angle",
        "framing": "Upper Body",
        "lens": "85mm (portrait)",
        "nsfw_shot": "Bent over from behind framing",
        "composition": "Emphasis on chest",
    },
    {
        "id": "camera_preset_20",
        "label": "Глубокий мужской взгляд (POV)",
        "hint": "Low Angle + Close-Up + 85mm + POV (male gaze)",
        "angle": "Low Angle",
        "framing": "Close-Up",
        "lens": "85mm (portrait)",
        "nsfw_shot": "POV (male gaze)",
    },
    {
        "id": "camera_preset_21",
        "label": "Покорная поза сверху",
        "hint": "High Angle + Cowboy Shot + 50mm + Looking down from above",
        "angle": "High Angle",
        "framing": "Cowboy Shot (thighs)",
        "lens": "50mm (standard)",
        "nsfw_shot": "Looking down from above",
    },
    {
        "id": "camera_preset_22",
        "label": "Тело в низком ракурсе",
        "hint": "Low Angle + Full Body + 35mm + Focus on body curves",
        "angle": "Low Angle",
        "framing": "Full Body",
        "lens": "35mm",
        "composition": "Focus on body curves",
    },
    {
        "id": "camera_preset_23",
        "label": "Интимный крупный план губ/глаз",
        "hint": "Extreme Close-Up + 105mm + Shallow Depth of Field + Extreme close-up on lips",
        "framing": "Extreme Close-Up (face/eyes/lips)",
        "lens": "105mm",
        "focus": "Shallow Depth of Field",
        "nsfw_shot": "Extreme close-up on lips",
    },
    {
        "id": "camera_preset_24",
        "label": "Напряжённый Dutch Angle",
        "hint": "Dutch Angle + Medium Shot + 50mm + Dutch angle erotic tension",
        "angle": "Dutch Angle",
        "framing": "Medium Shot",
        "lens": "50mm (standard)",
        "nsfw_shot": "Dutch angle erotic tension",
    },
    {
        "id": "camera_preset_25",
        "label": "Доминирование над фигурой",
        "hint": "Low Angle + Full Body with space + 35mm + Low angle dominance shot",
        "angle": "Low Angle",
        "framing": "Full Body with space",
        "lens": "35mm",
        "nsfw_shot": "Low angle dominance shot",
    },
    {
        "id": "camera_preset_26",
        "label": "Согнута и выставлена",
        "hint": "Low Angle + Cowboy Shot + 35mm + Bent over framing + Emphasis on ass",
        "angle": "Low Angle",
        "framing": "Cowboy Shot (thighs)",
        "lens": "35mm",
        "nsfw_shot": "Bent over from behind framing",
        "composition": "Emphasis on ass (from behind)",
    },
    {
        "id": "camera_preset_27",
        "label": "Ноги широко расставлены",
        "hint": "Low Angle + Medium Shot + 50mm + Legs spread framing",
        "angle": "Low Angle",
        "framing": "Medium Shot",
        "lens": "50mm (standard)",
        "nsfw_shot": "Legs spread framing",
    },
    {
        "id": "camera_preset_28",
        "label": "Полностью во власти кадра",
        "hint": "High Angle + Full Body + 35mm + Looking down from above + Focus on body curves",
        "angle": "High Angle",
        "framing": "Full Body",
        "lens": "35mm",
        "nsfw_shot": "Looking down from above",
        "composition": "Focus on body curves",
    },
    {
        "id": "camera_preset_29",
        "label": "Захвачена и удерживается",
        "hint": "Low Angle + Upper Body + 50mm + Low angle dominance shot",
        "angle": "Low Angle",
        "framing": "Upper Body",
        "lens": "50mm (standard)",
        "nsfw_shot": "Low angle dominance shot",
    },
    {
        "id": "camera_preset_30",
        "label": "Максимально провокационный POV",
        "hint": "POV + Close-Up + 50mm + POV from below + Intimate close framing",
        "angle": "POV (first person)",
        "framing": "Close-Up",
        "lens": "50mm (standard)",
        "nsfw_shot": "POV from below",
        "composition": "Intimate close framing",
    },
]

# Compatibility warnings — label tuples resolved at build time
CAMERA_COMPAT_WARNINGS: list[dict] = [
    {
        "message": "Low angle + extreme close-up may heavily distort the face.",
        "angle_labels": [
            "Low Angle",
            "Extreme Low Angle",
            "Low Angle looking up (dominance)",
            "Low Angle from floor level",
        ],
        "framing_labels": [
            "Extreme Close-Up (face/eyes/lips)",
            "Tight Close-Up",
        ],
    },
    {
        "message": "High angle + full body can look awkward — check composition.",
        "angle_labels": [
            "High Angle",
            "Extreme High Angle",
            "High Angle looking down (vulnerability)",
            "High Angle from above (submission)",
        ],
        "framing_labels": ["Full Body", "Full Body with space", "Wide Shot", "Extreme Wide Shot"],
    },
    {
        "message": "24mm close-up causes strong facial distortion.",
        "lens_labels": ["24mm (wide angle)"],
        "framing_labels": [
            "Extreme Close-Up (face/eyes/lips)",
            "Close-Up",
            "Tight Close-Up",
            "Portrait",
        ],
    },
    {
        "message": "105mm + full body compresses the figure too much.",
        "lens_labels": ["105mm", "135mm (strong compression)"],
        "framing_labels": ["Full Body", "Full Body with space", "Wide Shot", "Extreme Wide Shot"],
    },
    {
        "message": "Dutch angle works best with dynamic or tense poses.",
        "angle_labels": ["Dutch Angle", "Dutch Angle for tension"],
        "requires_static_pose": True,
    },
    {
        "message": "Extreme close-up pairs best with 85mm or 105mm lenses.",
        "framing_labels": ["Extreme Close-Up (face/eyes/lips)", "Tight Close-Up"],
        "lens_labels": ["24mm (wide angle)", "35mm"],
    },
    {
        "message": "Full body framing works best with 24–50mm lenses.",
        "framing_labels": ["Full Body", "Full Body with space"],
        "lens_labels": ["85mm (portrait)", "105mm", "135mm (strong compression)"],
    },
]

# Lens × pose auto-fix (extends legacy hardcoded rule)
CAMERA_LENS_POSE_FIXES: list[dict] = [
    {
        "lens_label": "85mm (portrait)",
        "pose_ids": ["on_all_fours_ass_high_chest_low"],
        "target_lens_label": "35mm",
        "message": "Lens auto-switched to 35mm for floor pose visibility.",
    },
    {
        "lens_label": "105mm",
        "pose_ids": ["on_all_fours_ass_high_chest_low"],
        "target_lens_label": "35mm",
        "message": "Lens auto-switched to 35mm for floor pose visibility.",
    },
]
