"""English label → Russian tooltip text for tag chips."""

from __future__ import annotations

import re

# Exact translations for character catalog (preferred over heuristic).
CHARACTER_EXACT: dict[str, str] = {
    "18–20 (young adult)": "18–20 (молодой взрослый)",
    "21–25": "21–25 лет",
    "26–30": "26–30 лет",
    "31–35": "31–35 лет",
    "36–40": "36–40 лет",
    "Mature beauty (35–45)": "Зрелая красота (35–45)",
    "MILF appearance": "Облик MILF",
    "Ageless / Timeless beauty": "Безвозрастная / вечная красота",
    "Slim / Slender": "Стройная / худощавая",
    "Petite": "Миниатюрная",
    "Athletic / Toned": "Атлетичная / подтянутая",
    "Fit": "Спортивная фигура",
    "Curvy": "Пышная фигура",
    "Voluptuous": "Соблазнительно пышная",
    "Hourglass figure": "Фигура «песочные часы»",
    "Slim-thick": "Slim-thick (стройная + формы)",
    "Soft / Chubby": "Мягкая / пышная",
    "Muscular feminine": "Мускулистая женственная",
    "Tall and elegant": "Высокая и элегантная",
    "Shortstack": "Shortstack (низкая + формы)",
    "Small breasts": "Маленькая грудь",
    "Medium breasts": "Средняя грудь",
    "Large breasts": "Большая грудь",
    "Very large breasts": "Очень большая грудь",
    "Huge breasts": "Огромная грудь",
    "Perky breasts": "Подтянутая грудь",
    "Round breasts": "Круглая грудь",
    "Teardrop breasts": "Грудь «капля»",
    "Full breasts": "Полная грудь",
    "Heavy breasts": "Тяжёлая грудь",
    "Natural breasts": "Натуральная грудь",
    "Firm breasts": "Упругая грудь",
    "Soft breasts": "Мягкая грудь",
    "Slim waist": "Тонкая талия",
    "Narrow waist": "Узкая талия",
    "Soft waist": "Мягкая талия",
    "Toned waist": "Подтянутая талия",
    "Defined waist": "Чётко выраженная талия",
    "Wide hips": "Широкие бёдра",
    "Thick thighs": "Полные бёдра",
    "Big ass": "Большая попа",
    "Round ass": "Круглая попа",
    "Heart-shaped ass": "Попа «сердечко»",
    "Bubble butt": "Округлая попа",
    "Plump ass": "Полная попа",
    "Firm ass": "Упругая попа",
    "Soft ass": "Мягкая попа",
    "Jiggly ass": "Подвижная попа",
    "Long legs": "Длинные ноги",
    "Toned legs": "Подтянутые ноги",
    "Slim legs": "Стройные ноги",
    "Muscular legs": "Мускулистые ноги",
    "Soft legs": "Мягкие ноги",
    "Long and elegant legs": "Длинные элегантные ноги",
    "Short and thick legs": "Короткие полные ноги",
    "Thigh gap": "Просвет между бёдрами",
    "Strong calves": "Сильные икры",
    "Smooth legs": "Гладкие ноги",
    "Legs with subtle muscle definition": "Ноги с лёгкой мускулатурой",
    "Hourglass proportions": "Пропорции «песочные часы»",
    "Curvy proportions": "Пышные пропорции",
    "Balanced proportions": "Сбалансированные пропорции",
    "Pear-shaped figure": "Фигура «груша»",
    "Voluptuous lower body": "Пышный низ тела",
    "Athletic proportions": "Атлетичные пропорции",
    "Very short / Petite": "Очень низкий рост / миниатюрная",
    "Short": "Низкий рост",
    "Average height": "Средний рост",
    "Tall": "Высокая",
    "Very tall": "Очень высокая",
    "Shortstack (short + curvy)": "Shortstack (низкая + формы)",
    "Tall and slender": "Высокая и стройная",
    "Tall and voluptuous": "Высокая и пышная",
    "Compact and curvy": "Компактная и пышная",
    "Caucasian": "Европеоидная",
    "East Asian": "Восточноазиатская",
    "Southeast Asian": "Юго-Восточная Азия",
    "South Asian": "Южноазиатская",
    "Latina": "Латиноамериканская",
    "Black / African": "Тёмная кожа / африканская",
    "Mixed": "Смешанная",
    "Arab / Middle Eastern": "Арабская / Ближний Восток",
    "Mediterranean": "Средиземноморская",
    "Slavic": "Славянская",
    "Nordic": "Скандинавская",
    "Eurasian": "Евразийская",
    "Fair / Porcelain": "Светлая / фарфоровая",
    "Light beige": "Светло-бежевая",
    "Warm tan": "Тёплый загар",
    "Golden / Olive": "Золотистая / оливковая",
    "Tan": "Загорелая",
    "Deep tan": "Глубокий загар",
    "Dark / Ebony": "Тёмная / эбеновая",
    "Pale with pink undertones": "Бледная с розовым подтоном",
    "Smooth skin": "Гладкая кожа",
    "Soft skin": "Мягкая кожа",
    "Silky skin": "Шёлковая кожа",
    "Toned skin": "Подтянутая кожа",
    "Oily / Shiny skin": "Жирная / блестящая кожа",
    "Dewy skin": "Сияющая влажная кожа",
    "Matte skin": "Матовая кожа",
    "Light sweat": "Лёгкий пот",
    "Glowing skin": "Сияющая кожа",
    "Light freckles on body": "Лёгкие веснушки на теле",
    "Beauty marks / moles": "Родинки / beauty marks",
    "Subtle stretch marks": "Едва заметные растяжки",
    "Light cellulite": "Лёгкий целлюлит",
    "Subtle muscle definition": "Лёгкая мускулатура",
    "Soft stomach": "Мягкий живот",
    "Toned stomach": "Подтянутый живот",
    "Sensitive skin": "Чувствительная кожа",
    "Easily flushed skin": "Легко краснеющая кожа",
    "none": "Без / выключено",
    "None": "Без / выключено",
}

PHRASE_RU: dict[str, str] = {
    "standing seductive": "стоя соблазнительно",
    "lying on bed": "лежит на кровати",
    "wide angle": "широкий угол",
    "portrait lens": "портретный объектив",
    "soft lighting": "мягкий свет",
    "hard lighting": "жёсткий свет",
    "natural light": "естественный свет",
    "anime style": "аниме-стиль",
    "close-up": "крупный план",
    "full body": "в полный рост",
    "upper body": "по пояс",
    "lower body": "нижняя часть тела",
    "from above": "сверху",
    "from below": "снизу",
    "eye level": "на уровне глаз",
    "low angle": "низкий ракурс",
    "high angle": "высокий ракурс",
    "dutch angle": "голландский угол",
    "side view": "вид сбоку",
    "front view": "анфас",
    "back view": "вид сзади",
    "three-quarter": "три четверти",
}

WORD_RU: dict[str, str] = {
    "a": "",
    "an": "",
    "the": "",
    "and": "и",
    "or": "или",
    "with": "с",
    "without": "без",
    "on": "на",
    "in": "в",
    "at": "у",
    "of": "",
    "to": "",
    "for": "для",
    "light": "лёгкий",
    "soft": "мягкий",
    "hard": "жёсткий",
    "strong": "сильный",
    "subtle": "лёгкий",
    "natural": "натуральный",
    "smooth": "гладкий",
    "silky": "шёлковый",
    "toned": "подтянутый",
    "defined": "чёткий",
    "wide": "широкий",
    "narrow": "узкий",
    "long": "длинный",
    "short": "короткий",
    "tall": "высокий",
    "small": "маленький",
    "medium": "средний",
    "large": "большой",
    "big": "большой",
    "huge": "огромный",
    "very": "очень",
    "deep": "глубокий",
    "dark": "тёмный",
    "pale": "бледный",
    "fair": "светлый",
    "warm": "тёплый",
    "golden": "золотистый",
    "glowing": "сияющий",
    "dewy": "влажный",
    "matte": "матовый",
    "oily": "жирный",
    "shiny": "блестящий",
    "sensitive": "чувствительный",
    "curvy": "пышный",
    "voluptuous": "соблазнительно пышный",
    "athletic": "атлетичный",
    "muscular": "мускулистый",
    "slim": "стройный",
    "slender": "худощавый",
    "petite": "миниатюрный",
    "fit": "спортивный",
    "round": "круглый",
    "firm": "упругий",
    "plump": "полный",
    "jiggly": "подвижный",
    "perky": "подтянутый",
    "full": "полный",
    "heavy": "тяжёлый",
    "teardrop": "каплевидный",
    "hourglass": "«песочные часы»",
    "balanced": "сбалансированный",
    "pear-shaped": "«груша»",
    "compact": "компактный",
    "average": "средний",
    "height": "рост",
    "skin": "кожа",
    "body": "тело",
    "face": "лицо",
    "hair": "волосы",
    "eyes": "глаза",
    "eye": "глаз",
    "lips": "губы",
    "mouth": "рот",
    "nose": "нос",
    "brows": "брови",
    "eyebrows": "брови",
    "jaw": "челюсть",
    "chin": "подбородок",
    "cheeks": "щёки",
    "breasts": "грудь",
    "breast": "грудь",
    "waist": "талия",
    "hips": "бёдра",
    "ass": "попа",
    "butt": "попа",
    "thighs": "бёдра",
    "thigh": "бедро",
    "legs": "ноги",
    "leg": "нога",
    "calves": "икры",
    "stomach": "живот",
    "figure": "фигура",
    "proportions": "пропорции",
    "ethnicity": "этничность",
    "tone": "тон",
    "freckles": "веснушки",
    "marks": "метки",
    "moles": "родинки",
    "stretch": "растяжки",
    "cellulite": "целлюлит",
    "muscle": "мышцы",
    "definition": "рельеф",
    "sweat": "пот",
    "flush": "румянец",
    "flushed": "краснеющий",
    "standing": "стоя",
    "sitting": "сидя",
    "lying": "лежа",
    "kneeling": "на коленях",
    "bed": "кровать",
    "seductive": "соблазнительный",
    "teasing": "дразнящий",
    "dynamic": "динамичный",
    "action": "действие",
    "pose": "поза",
    "camera": "камера",
    "angle": "ракурс",
    "lens": "объектив",
    "focus": "фокус",
    "framing": "кадрирование",
    "composition": "композиция",
    "lighting": "освещение",
    "shadow": "тень",
    "shadows": "тени",
    "ambient": "окружающий",
    "studio": "студийный",
    "outdoor": "уличный",
    "indoor": "интерьер",
    "night": "ночь",
    "day": "день",
    "sunset": "закат",
    "sunrise": "рассвет",
    "overcast": "пасмурно",
    "rain": "дождь",
    "snow": "снег",
    "fog": "туман",
    "location": "локация",
    "environment": "окружение",
    "room": "комната",
    "bedroom": "спальня",
    "bathroom": "ванная",
    "kitchen": "кухня",
    "office": "офис",
    "street": "улица",
    "beach": "пляж",
    "forest": "лес",
    "city": "город",
    "dress": "платье",
    "top": "верх",
    "bottom": "низ",
    "skirt": "юбка",
    "pants": "брюки",
    "shorts": "шорты",
    "shirt": "рубашка",
    "jacket": "куртка",
    "coat": "пальто",
    "shoes": "обувь",
    "heels": "каблуки",
    "boots": "ботинки",
    "stockings": "чулки",
    "gloves": "перчатки",
    "hat": "шляпа",
    "glasses": "очки",
    "jewelry": "украшения",
    "necklace": "ожерелье",
    "choker": "чокер",
    "makeup": "макияж",
    "lipstick": "помада",
    "eyeliner": "подводка",
    "blush": "румяна",
    "style": "стиль",
    "quality": "качество",
    "aesthetic": "эстетика",
    "technique": "техника",
    "artist": "художник",
    "anime": "аниме",
    "realistic": "реалистичный",
    "3d": "3D",
    "render": "рендер",
    "expression": "выражение",
    "smile": "улыбка",
    "ahegao": "ахэгао",
    "crying": "плач",
    "angry": "злость",
    "sad": "грусть",
    "happy": "радость",
    "neutral": "нейтральный",
    "cute": "милый",
    "serious": "серьёзный",
    "playful": "игривый",
    "mature": "зрелый",
    "young": "молодой",
    "adult": "взрослый",
    "beauty": "красота",
    "archetype": "архетип",
    "details": "детали",
    "texture": "текстура",
    "additional": "дополнительные",
    "appearance": "внешность",
    "color": "цвет",
    "red": "красный",
    "blue": "синий",
    "green": "зелёный",
    "blonde": "блонд",
    "black": "чёрный",
    "white": "белый",
    "pink": "розовый",
    "purple": "фиолетовый",
    "brown": "коричневый",
    "silver": "серебряный",
    "gold": "золотой",
    "fantasy": "фэнтези",
    "nsfw": "NSFW",
    "shot": "кадр",
    "close": "крупный",
    "up": "план",
    "portrait": "портрет",
    "standard": "стандартный",
    "compression": "сжатие",
    "position": "позиция",
    "abandoned": "заброшенный",
    "building": "здание",
    "warehouse": "склад",
    "interior": "интерьер",
    "exterior": "экстерьер",
    "kawaii": "кawaii",
    "adorable": "очаровательный",
    "vintage": "винтажный",
    "modern": "современный",
    "minimal": "минималистичный",
    "luxury": "роскошный",
    "casual": "повседневный",
    "formal": "формальный",
    "elegant": "элегантный",
    "sexy": "сексуальный",
    "erotic": "эротичный",
    "nude": "обнажённый",
    "topless": "топлесс",
    "sheer": "прозрачный",
    "wet": "мокрый",
    "torn": "рваный",
    "tight": "облегающий",
    "loose": "свободный",
    "open": "открытый",
    "closed": "закрытый",
    "partial": "частичный",
    "micro": "микро",
    "mini": "мини",
    "maxi": "макси",
    "layer": "слой",
    "underwear": "бельё",
    "bra": "лифчик",
    "panties": "трусы",
    "lingerie": "бельё",
    "bikini": "бикини",
    "swimsuit": "купальник",
    "uniform": "форма",
    "school": "школьный",
    "maid": "горничная",
    "nurse": "медсестра",
    "sport": "спортивный",
    "gym": "спортзал",
    "yoga": "йога",
    "dance": "танец",
    "couple": "пара",
    "solo": "соло",
    "group": "группа",
    "fetish": "фетиш",
    "bondage": "бондаж",
    "latex": "латекс",
    "leather": "кожа",
    "harness": "хarness",
    "collar": "ошейник",
    "chain": "цепь",
    "rope": "верёвка",
    "handcuffs": "наручники",
    "blindfold": "повязка",
    "gag": "кляп",
    "tail": "хвост",
    "ears": "уши",
    "horns": "рога",
    "wings": "крылья",
    "demon": "демон",
    "angel": "ангел",
    "elf": "эльф",
    "cat": "кошка",
    "bunny": "кролик",
    "fox": "лиса",
    "wolf": "волк",
    "vampire": "вампир",
    "witch": "ведьма",
    "season": "сезон",
    "spring": "весна",
    "summer": "лето",
    "autumn": "осень",
    "winter": "зима",
    "weather": "погода",
    "time": "время",
    "morning": "утро",
    "afternoon": "день",
    "evening": "вечер",
    "midnight": "полночь",
    "dawn": "рассвет",
    "dusk": "сумерки",
    "none": "без",
}


def _capitalize_ru(text: str) -> str:
    text = text.strip()
    if not text:
        return text
    return text[0].upper() + text[1:]


def _translate_tokens(label: str) -> str:
    parts = re.split(r"(\s+|/|,|\(|\)|\+|–|-)", label)
    out: list[str] = []
    for part in parts:
        if not part or re.fullmatch(r"[\s/,\(\)\+–\-]+", part):
            out.append(part)
            continue
        key = part.lower().strip(".")
        if key in WORD_RU:
            ru = WORD_RU[key]
            if not ru:
                continue
            if part[0].isupper():
                ru = _capitalize_ru(ru)
            out.append(ru)
        else:
            out.append(part)
    text = "".join(out)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\s+([,.])", r"\1", text)
    return text


def label_to_ru(label: str) -> str:
    if not label:
        return ""
    if label in CHARACTER_EXACT:
        return CHARACTER_EXACT[label]

    lowered = label.lower()
    if lowered == "none":
        return "Без / выключено"

    for phrase, ru in sorted(PHRASE_RU.items(), key=lambda item: -len(item[0])):
        if phrase in lowered:
            return _capitalize_ru(label.lower().replace(phrase, ru))

    translated = _translate_tokens(label)
    if re.search(r"[а-яА-ЯёЁ]", translated):
        return translated
    return label
